# Generated by Django 5.1.4 on 2025-11-14 15:51

import django.db.models.deletion
import scheduling.audit
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sop_document', models.TextField(blank=True, null=True)),
                ('sop_steps', models.JSONField(default=list)),
                ('is_critical', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_processes', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='accounts.restaurant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_processes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'processes',
                'ordering': ['-created_at'],
            },
            bases=(scheduling.audit.AuditMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProcessTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='TODO', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('due_time', models.TimeField(blank=True, null=True)),
                ('estimated_duration', models.DurationField(blank=True, null=True)),
                ('verification_type', models.CharField(choices=[('NONE', 'No Verification Required'), ('PHOTO', 'Photo Evidence Required'), ('DOCUMENT', 'Document Upload Required'), ('SIGNATURE', 'Digital Signature Required'), ('CHECKLIST', 'Checklist Completion Required'), ('SUPERVISOR_APPROVAL', 'Supervisor Approval Required')], default='NONE', max_length=30)),
                ('verification_required', models.BooleanField(default=False)),
                ('progress', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_process_tasks', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_tasks', to='scheduling.taskcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_process_tasks', to=settings.AUTH_USER_MODEL)),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='scheduling.processtask')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='scheduling.process')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_process_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'process_tasks',
                'ordering': ['due_date', 'priority'],
            },
            bases=(scheduling.audit.AuditMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['restaurant', 'status'], name='processes_restaur_3fe8cf_idx'),
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['is_active'], name='processes_is_acti_d0033d_idx'),
        ),
        migrations.AddIndex(
            model_name='processtask',
            index=models.Index(fields=['process', 'status'], name='process_tas_process_71de1a_idx'),
        ),
        migrations.AddIndex(
            model_name='processtask',
            index=models.Index(fields=['assigned_to', 'status'], name='process_tas_assigne_0ecdaa_idx'),
        ),
    ]
