# Generated by Django 4.2.13 on 2025-12-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_fix_assigned_shifts_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedshift',
            name='clock_out_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
