# Generated by Django 5.0 on 2025-10-27 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_add_task_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='shifttask',
            new_name='shift_tasks_shift_i_ca057f_idx',
            old_name='shift_tasks_shift_id_status_idx',
        ),
        migrations.RenameIndex(
            model_name='shifttask',
            new_name='shift_tasks_assigne_2f3a42_idx',
            old_name='shift_tasks_assigned_to_status_idx',
        ),
        migrations.AlterField(
            model_name='shifttask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
