# Generated by Django 4.2.13 on 2025-12-21 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_assignedshift_clock_out_reminder_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateshift',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='templateshift',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
