# Generated by Django 5.2.7 on 2025-10-27 03:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_geolocation_pos_ai'),
        ('scheduling', '0003_rename_shift_tasks_shift_id_status_idx_shift_tasks_shift_i_ca057f_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduletemplate',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='assignedshift',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignedshift',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20),
        ),
        migrations.AddField(
            model_name='scheduletemplate',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduletemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='assignedshift',
            index=models.Index(fields=['staff', 'shift_date'], name='assigned_sh_staff_i_dec37e_idx'),
        ),
        migrations.AddIndex(
            model_name='assignedshift',
            index=models.Index(fields=['status', 'shift_date'], name='assigned_sh_status_1439b9_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduletemplate',
            index=models.Index(fields=['restaurant', 'is_active'], name='schedule_te_restaur_e16a6a_idx'),
        ),
        migrations.AlterModelTable(
            name='assignedshift',
            table='assigned_shifts',
        ),
        migrations.AlterModelTable(
            name='scheduletemplate',
            table='schedule_templates',
        ),
    ]
