# Generated by Django 5.2.7 on 2025-10-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_alter_scheduletemplate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedshift',
            name='color',
            field=models.CharField(blank=True, default='#6b7280', max_length=7, null=True),
        ),
    ]
