# Generated by Django 4.2.13 on 2026-01-19 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduling', '0005_alter_assignedshift_role_alter_templateshift_role'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='assignedshift',
            name='assigned_sh_staff_i_dec37e_idx',
        ),
        migrations.AddField(
            model_name='assignedshift',
            name='staff_members',
            field=models.ManyToManyField(blank=True, related_name='assigned_shifts_m2m', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignedshift',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_shifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='assignedshift',
            index=models.Index(fields=['shift_date'], name='assigned_sh_shift_d_3457ed_idx'),
        ),
    ]
