# Generated by Django 5.2.7 on 2025-10-28 22:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_merge_20251028_1730'),
        ('scheduling', '0005_add_color_to_assignedshift'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_timesheets', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='accounts.restaurant')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'timesheets',
                'ordering': ['-end_date'],
            },
        ),
        migrations.CreateModel(
            name='TimesheetEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=6)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.assignedshift')),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='scheduling.timesheet')),
            ],
            options={
                'db_table': 'timesheet_entries',
            },
        ),
        migrations.AddIndex(
            model_name='timesheet',
            index=models.Index(fields=['staff', 'status'], name='timesheets_staff_i_379135_idx'),
        ),
        migrations.AddIndex(
            model_name='timesheet',
            index=models.Index(fields=['restaurant', 'status'], name='timesheets_restaur_be3009_idx'),
        ),
        migrations.AddIndex(
            model_name='timesheet',
            index=models.Index(fields=['end_date'], name='timesheets_end_dat_d5cb14_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='timesheet',
            unique_together={('staff', 'start_date', 'end_date', 'restaurant')},
        ),
        migrations.AlterUniqueTogether(
            name='timesheetentry',
            unique_together={('timesheet', 'shift')},
        ),
    ]
