# Generated by Django 5.1.4 on 2025-11-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_alter_assignedshift_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedshift',
            name='task_templates',
            field=models.ManyToManyField(blank=True, help_text='Task templates assigned to this shift for staff checklist', related_name='assigned_shifts', to='scheduling.tasktemplate'),
        ),
    ]
