# Generated by Django 5.2.7 on 2025-10-31 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_tasktemplate_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='progress_percentage',
            field=models.IntegerField(default=0, help_text='Progress percentage (0-100)'),
        ),
        migrations.AddField(
            model_name='task',
            name='progress_notes',
            field=models.TextField(blank=True, help_text='Notes about current progress', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='checkpoints',
            field=models.JSONField(default=list, help_text='Progress checkpoints with timestamps and photos'),
        ),
        migrations.AddField(
            model_name='task',
            name='completion_photo',
            field=models.ImageField(blank=True, help_text='Photo evidence of task completion', null=True, upload_to='task_completions/'),
        ),
        migrations.AddField(
            model_name='task',
            name='completion_location',
            field=models.CharField(blank=True, help_text='Location where task was completed', max_length=255, null=True),
        ),
    ]
