# Generated by Django 5.2.7 on 2025-10-31 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_auto_20251031_0358'),
    ]

    operations = [
    ]
