# Generated by Django 4.2.13 on 2026-01-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0009_timeoffrequest_staffavailability_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedshift',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='Whether this shift was created as part of a recurring series'),
        ),
        migrations.AddField(
            model_name='assignedshift',
            name='recurrence_group_id',
            field=models.UUIDField(blank=True, help_text='ID to group shifts created in the same recurring series', null=True),
        ),
    ]
