# Generated by Django 5.2.7 on 2025-10-31 12:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0011_alter_auditlog_object_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskComplianceCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_name', models.CharField(help_text='Name of the compliance check', max_length=255)),
                ('check_description', models.TextField(help_text='Description of what needs to be checked')),
                ('check_criteria', models.JSONField(default=dict, help_text='Specific criteria for passing this check')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('REQUIRES_ATTENTION', 'Requires Attention')], default='NOT_STARTED', max_length=20)),
                ('result_data', models.JSONField(default=dict, help_text='Data collected during the check')),
                ('pass_criteria_met', models.BooleanField(default=False)),
                ('supervisor_reviewed', models.BooleanField(default=False)),
                ('supervisor_notes', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('regulation_reference', models.CharField(blank=True, help_text='Reference to specific regulation or standard', max_length=255, null=True)),
                ('compliance_level', models.CharField(blank=True, help_text='Level of compliance required (e.g., FDA, OSHA)', max_length=50, null=True)),
            ],
            options={
                'db_table': 'task_compliance_checks',
                'ordering': ['check_name'],
            },
        ),
        migrations.CreateModel(
            name='TaskVerificationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo_evidence', models.JSONField(default=list, help_text='List of photo URLs/paths as evidence')),
                ('document_evidence', models.JSONField(default=list, help_text='List of document URLs/paths as evidence')),
                ('signature_data', models.TextField(blank=True, help_text='Digital signature data', null=True)),
                ('checklist_responses', models.JSONField(default=dict, help_text='Responses to verification checklist items')),
                ('temperature_readings', models.JSONField(default=list, help_text='Temperature readings with timestamps')),
                ('quantity_counts', models.JSONField(default=dict, help_text='Quantity counts and measurements')),
                ('measurement_data', models.JSONField(default=dict, help_text='Other measurement data')),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REQUIRES_REVISION', 'Requires Revision')], default='PENDING', max_length=20)),
                ('verification_notes', models.TextField(blank=True, help_text='Notes from verifier', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if applicable', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('gps_coordinates', models.JSONField(default=dict, help_text='GPS coordinates where verification was submitted')),
                ('location_verified', models.BooleanField(default=False, help_text='Whether location was verified')),
            ],
            options={
                'db_table': 'task_verification_records',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived'), ('DEPRECATED', 'Deprecated')], default='DRAFT', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('changes_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('template_data', models.JSONField(default=dict, help_text='Snapshot of template configuration')),
                ('shifts_data', models.JSONField(default=list, help_text='Snapshot of template shifts')),
            ],
            options={
                'db_table': 'template_versions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_log_timesta_c74bd9_idx',
            old_name='audit_log_timesta_b8b8c7_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_log_user_id_f94cfc_idx',
            old_name='audit_log_user_id_b8b8c7_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_log_content_10f046_idx',
            old_name='audit_log_content_b8b8c7_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_log_action_a34304_idx',
            old_name='audit_log_action_b8b8c7_idx',
        ),
        migrations.AddField(
            model_name='assignedshift',
            name='compliance_checks_required',
            field=models.JSONField(default=list, help_text='List of required compliance checks'),
        ),
        migrations.AddField(
            model_name='assignedshift',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignedshift',
            name='department',
            field=models.CharField(blank=True, help_text='Department assignment', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assignedshift',
            name='equipment_needed',
            field=models.JSONField(default=list, help_text='List of required equipment/tools'),
        ),
        migrations.AddField(
            model_name='assignedshift',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_shifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignedshift',
            name='notification_channels',
            field=models.JSONField(default=list, help_text='Channels used for notification (whatsapp, email, app)'),
        ),
        migrations.AddField(
            model_name='assignedshift',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignedshift',
            name='notification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignedshift',
            name='preparation_instructions',
            field=models.TextField(blank=True, help_text='Special preparation instructions', null=True),
        ),
        migrations.AddField(
            model_name='assignedshift',
            name='required_certifications',
            field=models.JSONField(default=list, help_text='List of required certifications'),
        ),
        migrations.AddField(
            model_name='assignedshift',
            name='required_skills',
            field=models.JSONField(default=list, help_text='List of required skills for this shift'),
        ),
        migrations.AddField(
            model_name='assignedshift',
            name='safety_briefing_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignedshift',
            name='safety_briefing_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignedshift',
            name='safety_briefing_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignedshift',
            name='timezone',
            field=models.CharField(default='UTC', help_text='Timezone for shift times', max_length=50),
        ),
        migrations.AddField(
            model_name='assignedshift',
            name='workspace_location',
            field=models.CharField(blank=True, help_text='Specific workspace/station assignment', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shifttask',
            name='actual_duration',
            field=models.DurationField(blank=True, help_text='Actual time taken to complete task', null=True),
        ),
        migrations.AddField(
            model_name='shifttask',
            name='completion_percentage',
            field=models.IntegerField(default=0, help_text='Task completion percentage (0-100)'),
        ),
        migrations.AddField(
            model_name='shifttask',
            name='compliance_checks',
            field=models.JSONField(default=list, help_text='List of required compliance checks'),
        ),
        migrations.AddField(
            model_name='shifttask',
            name='depends_on_tasks',
            field=models.ManyToManyField(blank=True, help_text='Tasks that must be completed before this one', related_name='dependent_tasks', to='scheduling.shifttask'),
        ),
        migrations.AddField(
            model_name='shifttask',
            name='environmental_conditions',
            field=models.JSONField(default=dict, help_text='Required environmental conditions (temperature, humidity, etc.)'),
        ),
        migrations.AddField(
            model_name='shifttask',
            name='is_critical',
            field=models.BooleanField(default=False, help_text='Mark as critical task requiring immediate attention'),
        ),
        migrations.AddField(
            model_name='shifttask',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shifttask',
            name='last_maintenance_date',
            field=models.DateTimeField(blank=True, help_text='When this maintenance was last performed', null=True),
        ),
        migrations.AddField(
            model_name='shifttask',
            name='location_specific',
            field=models.CharField(blank=True, help_text='Specific location where task should be performed', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shifttask',
            name='maintenance_frequency',
            field=models.CharField(blank=True, help_text='How often this maintenance should occur', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shifttask',
            name='maintenance_type',
            field=models.CharField(blank=True, help_text='Type of maintenance task', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shifttask',
            name='next_occurrence',
            field=models.DateTimeField(blank=True, help_text='When this task should next occur', null=True),
        ),
        migrations.AddField(
            model_name='shifttask',
            name='quality_standards',
            field=models.JSONField(default=list, help_text='Quality control standards to meet'),
        ),
        migrations.AddField(
            model_name='shifttask',
            name='recurrence_pattern',
            field=models.CharField(blank=True, help_text='Pattern for recurring tasks (daily, weekly, etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shifttask',
            name='required_certifications',
            field=models.JSONField(default=list, help_text='Certifications required for this task'),
        ),
        migrations.AddField(
            model_name='shifttask',
            name='required_equipment',
            field=models.JSONField(default=list, help_text='List of required equipment/tools'),
        ),
        migrations.AddField(
            model_name='shifttask',
            name='required_materials',
            field=models.JSONField(default=list, help_text='List of required materials/supplies'),
        ),
        migrations.AddField(
            model_name='shifttask',
            name='required_skills',
            field=models.JSONField(default=list, help_text='Skills required to complete this task'),
        ),
        migrations.AddField(
            model_name='shifttask',
            name='safety_requirements',
            field=models.JSONField(default=list, help_text='Safety requirements and protocols'),
        ),
        migrations.AddField(
            model_name='shifttask',
            name='sop_document',
            field=models.TextField(blank=True, help_text='Standard Operating Procedure instructions', null=True),
        ),
        migrations.AddField(
            model_name='shifttask',
            name='sop_steps',
            field=models.JSONField(default=list, help_text='Step-by-step SOP instructions as JSON array'),
        ),
        migrations.AddField(
            model_name='shifttask',
            name='sop_version',
            field=models.CharField(blank=True, help_text='SOP version number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shifttask',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='When task was started', null=True),
        ),
        migrations.AddField(
            model_name='shifttask',
            name='supervisor_notification_required',
            field=models.BooleanField(default=False, help_text='Notify supervisor when task status changes'),
        ),
        migrations.AddField(
            model_name='shifttask',
            name='verification_checklist',
            field=models.JSONField(default=list, help_text='Checklist items for verification'),
        ),
        migrations.AddField(
            model_name='shifttask',
            name='verification_instructions',
            field=models.TextField(blank=True, help_text='Instructions for verification process', null=True),
        ),
        migrations.AddField(
            model_name='shifttask',
            name='verification_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shifttask',
            name='verification_type',
            field=models.CharField(choices=[('NONE', 'No Verification Required'), ('PHOTO', 'Photo Evidence Required'), ('DOCUMENT', 'Document Upload Required'), ('SIGNATURE', 'Digital Signature Required'), ('CHECKLIST', 'Checklist Completion Required'), ('SUPERVISOR_APPROVAL', 'Supervisor Approval Required'), ('TEMPERATURE_LOG', 'Temperature Recording Required'), ('QUANTITY_COUNT', 'Quantity/Count Recording Required')], default='NONE', max_length=30),
        ),
        migrations.AddField(
            model_name='task',
            name='actual_duration',
            field=models.DurationField(blank=True, help_text='Actual time taken to complete task', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='compliance_checks',
            field=models.JSONField(default=list, help_text='List of required compliance checks'),
        ),
        migrations.AddField(
            model_name='task',
            name='depends_on_tasks',
            field=models.ManyToManyField(blank=True, help_text='Tasks that must be completed before this one', related_name='dependent_tasks', to='scheduling.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='environmental_conditions',
            field=models.JSONField(default=dict, help_text='Required environmental conditions (temperature, humidity, etc.)'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_critical',
            field=models.BooleanField(default=False, help_text='Mark as critical task requiring immediate attention'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='When task was last updated'),
        ),
        migrations.AddField(
            model_name='task',
            name='location_specific',
            field=models.CharField(blank=True, help_text='Specific location where task should be performed', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='next_occurrence',
            field=models.DateTimeField(blank=True, help_text='When this task should next occur', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='quality_standards',
            field=models.JSONField(default=list, help_text='Quality control standards to meet'),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence_pattern',
            field=models.CharField(blank=True, help_text='Pattern for recurring tasks (daily, weekly, etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='required_certifications',
            field=models.JSONField(default=list, help_text='Certifications required for this task'),
        ),
        migrations.AddField(
            model_name='task',
            name='required_equipment',
            field=models.JSONField(default=list, help_text='List of required equipment/tools'),
        ),
        migrations.AddField(
            model_name='task',
            name='required_materials',
            field=models.JSONField(default=list, help_text='List of required materials/supplies'),
        ),
        migrations.AddField(
            model_name='task',
            name='required_skills',
            field=models.JSONField(default=list, help_text='Skills required to complete this task'),
        ),
        migrations.AddField(
            model_name='task',
            name='safety_requirements',
            field=models.JSONField(default=list, help_text='Safety requirements and protocols'),
        ),
        migrations.AddField(
            model_name='task',
            name='sop_document',
            field=models.TextField(blank=True, help_text='Standard Operating Procedure instructions', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='sop_steps',
            field=models.JSONField(default=list, help_text='Step-by-step SOP instructions as JSON array'),
        ),
        migrations.AddField(
            model_name='task',
            name='sop_version',
            field=models.CharField(blank=True, help_text='SOP version number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='When task was started', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='supervisor_notification_required',
            field=models.BooleanField(default=False, help_text='Notify supervisor when task status changes'),
        ),
        migrations.AddField(
            model_name='task',
            name='verification_checklist',
            field=models.JSONField(default=list, help_text='Checklist items for verification'),
        ),
        migrations.AddField(
            model_name='task',
            name='verification_instructions',
            field=models.TextField(blank=True, help_text='Instructions for verification process', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='verification_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='verification_type',
            field=models.CharField(choices=[('NONE', 'No Verification Required'), ('PHOTO', 'Photo Evidence Required'), ('DOCUMENT', 'Document Upload Required'), ('SIGNATURE', 'Digital Signature Required'), ('CHECKLIST', 'Checklist Completion Required'), ('SUPERVISOR_APPROVAL', 'Supervisor Approval Required'), ('TEMPERATURE_LOG', 'Temperature Recording Required'), ('QUANTITY_COUNT', 'Quantity/Count Recording Required')], default='NONE', max_length=30),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='compliance_checks',
            field=models.JSONField(default=list, help_text='List of required compliance checks'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='difficulty_level',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('EXPERT', 'Expert')], default='INTERMEDIATE', max_length=20),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='estimated_duration',
            field=models.DurationField(blank=True, help_text='Estimated time to complete all tasks', null=True),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='is_critical',
            field=models.BooleanField(default=False, help_text='Mark as critical template requiring immediate attention'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='is_latest_version',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='last_used',
            field=models.DateTimeField(blank=True, help_text='When this template was last used', null=True),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='parent_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='scheduling.tasktemplate'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='priority_level',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='quality_standards',
            field=models.JSONField(default=list, help_text='Quality control standards to meet'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='regulatory_requirements',
            field=models.JSONField(default=list, help_text='Regulatory compliance requirements'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='required_certifications',
            field=models.JSONField(default=list, help_text='Certifications required for tasks in this template'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='required_equipment',
            field=models.JSONField(default=list, help_text='List of required equipment/tools'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='required_materials',
            field=models.JSONField(default=list, help_text='List of required materials/supplies'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='required_skills',
            field=models.JSONField(default=list, help_text='Skills required to complete tasks in this template'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='requires_approval',
            field=models.BooleanField(default=False, help_text='Whether tasks from this template require supervisor approval'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='safety_requirements',
            field=models.JSONField(default=list, help_text='Safety requirements and protocols'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='sop_document',
            field=models.TextField(blank=True, help_text='Standard Operating Procedure instructions', null=True),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='sop_last_updated',
            field=models.DateTimeField(blank=True, help_text='When SOP was last updated', null=True),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='sop_steps',
            field=models.JSONField(default=list, help_text='Step-by-step SOP instructions as JSON array'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='sop_version',
            field=models.CharField(blank=True, help_text='SOP version number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='usage_count',
            field=models.IntegerField(default=0, help_text='Number of times this template has been used'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='verification_checklist',
            field=models.JSONField(default=list, help_text='Checklist items for verification'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='verification_instructions',
            field=models.TextField(blank=True, help_text='Instructions for verification process', null=True),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='verification_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='verification_type',
            field=models.CharField(choices=[('NONE', 'No Verification Required'), ('PHOTO', 'Photo Evidence Required'), ('DOCUMENT', 'Document Upload Required'), ('SIGNATURE', 'Digital Signature Required'), ('CHECKLIST', 'Checklist Completion Required'), ('SUPERVISOR_APPROVAL', 'Supervisor Approval Required'), ('TEMPERATURE_LOG', 'Temperature Recording Required'), ('QUANTITY_COUNT', 'Quantity/Count Recording Required')], default='NONE', max_length=30),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='version',
            field=models.CharField(default='1.0', help_text='Template version number', max_length=20),
        ),
        migrations.AlterField(
            model_name='assignedshift',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], default='SCHEDULED', max_length=20),
        ),
        migrations.AlterField(
            model_name='tasktemplate',
            name='frequency',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUALLY', 'Annually'), ('CUSTOM', 'Custom')], default='DAILY', max_length=20),
        ),
        migrations.AlterField(
            model_name='tasktemplate',
            name='template_type',
            field=models.CharField(choices=[('CLEANING', 'Daily Restaurant Cleaning Schedule'), ('TEMPERATURE', 'Daily Temperature Log'), ('OPENING', 'Restaurant Manager Opening Checklist'), ('CLOSING', 'Restaurant Manager Closing Checklist'), ('HEALTH', 'Monthly Health and Safety Inspection'), ('SOP', 'Standard Operating Procedure'), ('MAINTENANCE', 'Equipment Maintenance'), ('COMPLIANCE', 'Compliance Check'), ('SAFETY', 'Safety Protocol'), ('QUALITY', 'Quality Control'), ('CUSTOM', 'Custom Template')], max_length=20),
        ),
        migrations.AddField(
            model_name='taskcompliancecheck',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_compliance_checks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskcompliancecheck',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_check_records', to='scheduling.shifttask'),
        ),
        migrations.AddField(
            model_name='taskverificationrecord',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskverificationrecord',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_records', to='scheduling.shifttask'),
        ),
        migrations.AddField(
            model_name='taskverificationrecord',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='templateversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='templateversion',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='scheduling.scheduletemplate'),
        ),
        migrations.AddIndex(
            model_name='taskcompliancecheck',
            index=models.Index(fields=['task', 'status'], name='task_compli_task_id_98d4ff_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcompliancecheck',
            index=models.Index(fields=['status', 'completed_at'], name='task_compli_status_f571db_idx'),
        ),
        migrations.AddIndex(
            model_name='taskverificationrecord',
            index=models.Index(fields=['task', 'verification_status'], name='task_verifi_task_id_53a25c_idx'),
        ),
        migrations.AddIndex(
            model_name='taskverificationrecord',
            index=models.Index(fields=['submitted_by', 'submitted_at'], name='task_verifi_submitt_d71532_idx'),
        ),
        migrations.AddIndex(
            model_name='templateversion',
            index=models.Index(fields=['template', 'status'], name='template_ve_templat_e43452_idx'),
        ),
        migrations.AddIndex(
            model_name='templateversion',
            index=models.Index(fields=['status', 'created_at'], name='template_ve_status_c8a8ae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='templateversion',
            unique_together={('template', 'version_number')},
        ),
    ]
