# Generated by Django 4.2.13 on 2026-02-08 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0011_shiftchecklistprogress'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='shiftchecklistprogress',
            new_name='shift_check_staff_i_e509fe_idx',
            old_name='shift_check_staff_i_idx',
        ),
        migrations.RenameIndex(
            model_name='shiftchecklistprogress',
            new_name='shift_check_phone_61cead_idx',
            old_name='shift_check_phone__idx',
        ),
    ]
