# Generated by Django 4.2.13 on 2026-02-08 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_rename_staff_resta_restaur_idx_staff_resta_restaur_657633_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduling', '0012_rename_shift_check_staff_i_idx_shift_check_staff_i_e509fe_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentMemory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('memory_type', models.CharField(choices=[('preference', 'Preference'), ('correction', 'Correction'), ('fact', 'Fact'), ('pattern', 'Pattern')], db_index=True, default='fact', max_length=20)),
                ('key', models.CharField(help_text='E.g. staff name, "no_maria_fridays", "default_breakfast_time"', max_length=255)),
                ('value', models.TextField(help_text='Stored fact or instruction')),
                ('scope', models.CharField(blank=True, help_text='Optional: staff_id, role, or date range', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_memories_created', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_memories', to='accounts.restaurant')),
            ],
            options={
                'verbose_name_plural': 'Agent memories',
                'db_table': 'agent_memories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['restaurant', 'memory_type'], name='agent_memor_restaur_d67ed7_idx'), models.Index(fields=['restaurant', 'key'], name='agent_memor_restaur_229e80_idx')],
            },
        ),
    ]
