# Generated by Django 5.2.7 on 2025-11-01 06:37

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_staffinvitation_extra_data_staffprofile_department'),
        ('scheduling', '0013_create_task_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['due_date', 'due_time', 'priority']},
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='template_ta_due_dat_f364c4_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='template_ta_priorit_3d350b_idx',
        ),
        migrations.AddField(
            model_name='task',
            name='actual_duration',
            field=models.DurationField(blank=True, help_text='Actual time taken to complete task', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='checkpoints',
            field=models.JSONField(default=list, help_text='Progress checkpoints with timestamps and photos'),
        ),
        migrations.AddField(
            model_name='task',
            name='completion_location',
            field=models.CharField(blank=True, help_text='Location where task was completed', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='completion_photo',
            field=models.ImageField(blank=True, help_text='Photo evidence of task completion', null=True, upload_to='task_completions/'),
        ),
        migrations.AddField(
            model_name='task',
            name='compliance_checks',
            field=models.JSONField(default=list, help_text='List of required compliance checks'),
        ),
        migrations.AddField(
            model_name='task',
            name='depends_on_tasks',
            field=models.ManyToManyField(blank=True, help_text='Tasks that must be completed before this one', related_name='dependent_tasks', to='scheduling.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='environmental_conditions',
            field=models.JSONField(default=dict, help_text='Required environmental conditions (temperature, humidity, etc.)'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_critical',
            field=models.BooleanField(default=False, help_text='Mark as critical task requiring immediate attention'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='When task was last updated'),
        ),
        migrations.AddField(
            model_name='task',
            name='location_specific',
            field=models.CharField(blank=True, help_text='Specific location where task should be performed', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='next_occurrence',
            field=models.DateTimeField(blank=True, help_text='When this task should next occur', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='progress_notes',
            field=models.TextField(blank=True, help_text='Notes about current progress', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='progress_percentage',
            field=models.IntegerField(default=0, help_text='Progress percentage (0-100)'),
        ),
        migrations.AddField(
            model_name='task',
            name='quality_standards',
            field=models.JSONField(default=list, help_text='Quality control standards to meet'),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence_pattern',
            field=models.CharField(blank=True, help_text='Pattern for recurring tasks (daily, weekly, etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='reminder_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='task',
            name='reminder_time',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
        migrations.AddField(
            model_name='task',
            name='required_certifications',
            field=models.JSONField(default=list, help_text='Certifications required for this task'),
        ),
        migrations.AddField(
            model_name='task',
            name='required_equipment',
            field=models.JSONField(default=list, help_text='List of required equipment/tools'),
        ),
        migrations.AddField(
            model_name='task',
            name='required_materials',
            field=models.JSONField(default=list, help_text='List of required materials/supplies'),
        ),
        migrations.AddField(
            model_name='task',
            name='required_skills',
            field=models.JSONField(default=list, help_text='Skills required to complete this task'),
        ),
        migrations.AddField(
            model_name='task',
            name='safety_requirements',
            field=models.JSONField(default=list, help_text='Safety requirements and protocols'),
        ),
        migrations.AddField(
            model_name='task',
            name='sop_document',
            field=models.TextField(blank=True, help_text='Standard Operating Procedure instructions', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='sop_steps',
            field=models.JSONField(default=list, help_text='Step-by-step SOP instructions as JSON array'),
        ),
        migrations.AddField(
            model_name='task',
            name='sop_version',
            field=models.CharField(blank=True, help_text='SOP version number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='When task was started', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='supervisor_notification_required',
            field=models.BooleanField(default=False, help_text='Notify supervisor when task status changes'),
        ),
        migrations.AddField(
            model_name='task',
            name='verification_checklist',
            field=models.JSONField(default=list, help_text='Checklist items for verification'),
        ),
        migrations.AddField(
            model_name='task',
            name='verification_instructions',
            field=models.TextField(blank=True, help_text='Instructions for verification process', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='verification_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='verification_type',
            field=models.CharField(choices=[('NONE', 'No Verification Required'), ('PHOTO', 'Photo Evidence Required'), ('DOCUMENT', 'Document Upload Required'), ('SIGNATURE', 'Digital Signature Required'), ('CHECKLIST', 'Checklist Completion Required'), ('SUPERVISOR_APPROVAL', 'Supervisor Approval Required'), ('TEMPERATURE_LOG', 'Temperature Recording Required'), ('QUANTITY_COUNT', 'Quantity/Count Recording Required')], default='NONE', max_length=30),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date'], name='template_ta_due_dat_f364c4_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['priority'], name='template_ta_priorit_3d350b_idx'),
        ),
    ]
