# Generated by Django 4.2.13 on 2026-02-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0013_agent_memory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View'), ('ASSIGN', 'Assign'), ('UNASSIGN', 'Unassign'), ('START', 'Start'), ('COMPLETE', 'Complete'), ('PAUSE', 'Pause'), ('RESUME', 'Resume'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('EXPORT', 'Export'), ('IMPORT', 'Import'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('BULK_UPDATE', 'Bulk Update'), ('TEMPLATE_APPLY', 'Template Apply'), ('SCHEDULE_PUBLISH', 'Schedule Publish'), ('SHIFT_SWAP', 'Shift Swap'), ('TASK_REASSIGN', 'Task Reassign'), ('PROGRESS_UPDATE', 'Progress Update'), ('CHECKPOINT_ADD', 'Checkpoint Add'), ('PHOTO_UPLOAD', 'Photo Upload'), ('AUTO_CLOCK_OUT', 'Auto Clock Out')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='shiftchecklistprogress',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('INCOMPLETE_SHIFT_END', 'Incomplete (shift ended)')], db_index=True, default='IN_PROGRESS', max_length=20),
        ),
    ]
