# Generated by Django 4.2.13 on 2026-04-09 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0015_shiftchecklistprogress_manager_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedshift',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('CHEF', 'Chef'), ('WAITER', 'Waiter'), ('KITCHEN_HELP', 'Kitchen Help'), ('BARTENDER', 'Bartender'), ('RECEPTIONIST', 'Receptionist'), ('CLEANER', 'Cleaner'), ('SECURITY', 'Security'), ('CASHIER', 'Cashier'), ('CUSTOM', 'Custom')], max_length=20),
        ),
        migrations.AlterField(
            model_name='templateshift',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('CHEF', 'Chef'), ('WAITER', 'Waiter'), ('KITCHEN_HELP', 'Kitchen Help'), ('BARTENDER', 'Bartender'), ('RECEPTIONIST', 'Receptionist'), ('CLEANER', 'Cleaner'), ('SECURITY', 'Security'), ('CASHIER', 'Cashier'), ('CUSTOM', 'Custom')], max_length=20),
        ),
    ]
