# Generated by Django 4.2.10 on 2026-04-18 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_customuser_allowed_locations_and_more'),
        ('scheduling', '0016_alter_assignedshift_role_alter_templateshift_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedshift',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_shifts', to='accounts.businesslocation'),
        ),
    ]
