# Generated by Django 4.2.13 on 2026-07-10 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_staffprofile_monthly_salary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduling', '0017_assignedshift_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('visibility', models.CharField(choices=[('personal', 'Personal'), ('team', 'Team (restaurant)'), ('department', 'Department')], default='personal', max_length=20)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_lists_owned', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_lists', to='accounts.restaurant')),
            ],
            options={
                'db_table': 'memory_lists',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MemoryNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visibility', models.CharField(choices=[('personal', 'Personal'), ('team', 'Team (restaurant)'), ('department', 'Department')], db_index=True, default='personal', max_length=20)),
                ('department', models.CharField(blank=True, default='', max_length=64)),
                ('content', models.TextField(help_text='What was said / saved')),
                ('why', models.TextField(blank=True, default='', help_text='Why it mattered / decision rationale')),
                ('people', models.JSONField(blank=True, default=list, help_text='People involved, e.g. ["Karim", "supplier Sysco"]')),
                ('entities', models.JSONField(blank=True, default=list, help_text='Named entities: brands, products, campaigns, sites')),
                ('project_key', models.CharField(blank=True, db_index=True, default='', help_text='Thread/project slug, e.g. "ramadan-2026", "terrace-redesign"', max_length=120)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('linked_task_id', models.UUIDField(blank=True, null=True)),
                ('linked_staff_request_id', models.UUIDField(blank=True, null=True)),
                ('linked_invoice_id', models.UUIDField(blank=True, null=True)),
                ('media_url', models.URLField(blank=True, default='', max_length=1000)),
                ('media_type', models.CharField(blank=True, default='', max_length=40)),
                ('source_channel', models.CharField(default='whatsapp', max_length=20)),
                ('source_phone', models.CharField(blank=True, default='', max_length=40)),
                ('last_recalled_at', models.DateTimeField(blank=True, null=True)),
                ('recall_count', models.PositiveIntegerField(default=0)),
                ('is_archived', models.BooleanField(default=False)),
                ('search_text', models.TextField(blank=True, default='', help_text='Denormalized blob for icontains / full-text search')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, help_text='Who saved this (personal scope filter).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_notes_owned', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_notes', to='accounts.restaurant')),
            ],
            options={
                'db_table': 'memory_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemoryListItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=500)),
                ('is_checked', models.BooleanField(default=False)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('memory_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='scheduling.memorylist')),
            ],
            options={
                'db_table': 'memory_list_items',
                'ordering': ['order_index', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonalReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, default='', help_text='E.164-ish digits for WhatsApp delivery', max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('due_at', models.DateTimeField(db_index=True)),
                ('timezone_name', models.CharField(default='Africa/Casablanca', max_length=64)),
                ('recurrence', models.CharField(choices=[('none', 'One-shot'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('weekdays', 'Weekdays (Mon–Fri)')], default='none', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fired', 'Fired'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('fired_at', models.DateTimeField(blank=True, null=True)),
                ('fire_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='scheduling.memorynote')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_reminders', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_reminders', to='accounts.restaurant')),
            ],
            options={
                'db_table': 'personal_reminders',
                'ordering': ['due_at'],
                'indexes': [models.Index(fields=['status', 'due_at'], name='personal_re_status_594b29_idx'), models.Index(fields=['restaurant', 'owner', 'status'], name='personal_re_restaur_a87efe_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='memorynote',
            index=models.Index(fields=['restaurant', 'visibility', '-created_at'], name='memory_note_restaur_6df75e_idx'),
        ),
        migrations.AddIndex(
            model_name='memorynote',
            index=models.Index(fields=['restaurant', 'project_key'], name='memory_note_restaur_270a7e_idx'),
        ),
        migrations.AddIndex(
            model_name='memorynote',
            index=models.Index(fields=['restaurant', 'owner', '-created_at'], name='memory_note_restaur_891bc4_idx'),
        ),
        migrations.AddIndex(
            model_name='memorylist',
            index=models.Index(fields=['restaurant', 'owner'], name='memory_list_restaur_14e9c7_idx'),
        ),
        migrations.AddConstraint(
            model_name='memorylist',
            constraint=models.UniqueConstraint(fields=('restaurant', 'owner', 'name'), name='uniq_memory_list_per_owner_name'),
        ),
    ]
