# Generated by Django 4.2.10 on 2026-07-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0018_memory_layer_notes_lists_reminders'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifttask',
            name='branch_config',
            field=models.JSONField(blank=True, default=dict, help_text='Yes/No condition flow from the process template (alert/goto/end).'),
        ),
    ]
