# Generated by Django 4.2.10 on 2026-07-15 14:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduling', '0019_shifttask_branch_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktemplate',
            name='standing_assignees',
            field=models.ManyToManyField(blank=True, help_text='Staff who can run this checklist after clock-in without a scheduled shift.', related_name='standing_task_templates', to=settings.AUTH_USER_MODEL),
        ),
    ]
