# Generated by Django 4.2.13 on 2026-07-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0020_tasktemplate_standing_assignees'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalreminder',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional file attached to the reminder (image, PDF, etc.).', null=True, upload_to='personal_reminders/'),
        ),
        migrations.AddField(
            model_name='personalreminder',
            name='attachment_url',
            field=models.URLField(blank=True, default='', help_text='External URL when the attachment is hosted off-platform.', max_length=1024),
        ),
    ]
