# Generated by Django 4.2.13 on 2026-07-30 06:19

import core.storage_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0021_personalreminder_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalreminder',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional file attached to the reminder (image, PDF, etc.).', null=True, upload_to=core.storage_paths.reminder_attachment_upload_path),
        ),
    ]
