# Generated by Django 4.2.10 on 2026-04-28 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0033_auditlog_memory_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=200)),
                ('invoice_number', models.CharField(blank=True, default='', help_text='Invoice number printed on the bill, used for dedupe.', max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('PAID', 'Paid'), ('VOIDED', 'Voided')], default='OPEN', max_length=12)),
                ('category', models.CharField(blank=True, default='', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('photo', models.ImageField(blank=True, help_text='Snapshot of the printed/PDF invoice.', null=True, upload_to='invoices/')),
                ('photo_url', models.URLField(blank=True, default='', help_text='External URL when the photo is hosted off-platform (e.g. WhatsApp media).', max_length=1024)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('BANK_TRANSFER', 'Bank transfer'), ('CHEQUE', 'Cheque'), ('DIRECT_DEBIT', 'Direct debit'), ('OTHER', 'Other')], default='', max_length=20)),
                ('payment_reference', models.CharField(blank=True, default='', help_text='Cheque number, transfer reference, or POS receipt id.', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_created', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, help_text='Which branch this bill belongs to (optional, defaults to tenant primary).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='accounts.businesslocation')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_paid', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='accounts.restaurant')),
            ],
            options={
                'ordering': ['due_date', '-created_at'],
                'indexes': [models.Index(fields=['restaurant', 'status', 'due_date'], name='finance_inv_restaur_e506e3_idx'), models.Index(fields=['restaurant', 'vendor_name', 'invoice_number'], name='finance_inv_restaur_8eb44f_idx')],
            },
        ),
    ]
