# Generated by Django 4.2.10 on 2026-07-14 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_prep_planning_fields'),
        ('finance', '0003_invoice_attachment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='match_confidence',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='0–1 score from the matcher when status is SUGGESTED/CONFIRMED.', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='match_status',
            field=models.CharField(choices=[('UNMATCHED', 'Unmatched'), ('SUGGESTED', 'Suggested'), ('CONFIRMED', 'Confirmed')], db_index=True, default='UNMATCHED', max_length=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='purchase_order',
            field=models.ForeignKey(blank=True, help_text='Linked purchase order when AP invoice is reconciled to a PO.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='inventory.purchaseorder'),
        ),
    ]
