# Generated by Django 4.2.10 on 2026-07-15 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0035_staffprofile_monthly_salary'),
        ('finance', '0004_invoice_po_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='approval_status',
            field=models.CharField(choices=[('NONE', 'Not required'), ('PENDING_APPROVAL', 'Pending approval'), ('APPROVED', 'Approved to pay'), ('REJECTED', 'Rejected')], db_index=True, default='NONE', help_text='PayGuard ladder status before mark-paid is allowed.', max_length=20),
        ),
        migrations.CreateModel(
            name='InvoicePaymentApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tier_id', models.CharField(blank=True, default='', max_length=64)),
                ('tier_name', models.CharField(blank=True, default='', max_length=120)),
                ('current_step_index', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_reminded_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_approval', to='finance.invoice')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_approvals_requested', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_approvals', to='accounts.restaurant')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoicePaymentApprovalStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_order', models.PositiveSmallIntegerField()),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('required_role', models.CharField(blank=True, default='', max_length=32)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('NOTIFIED', 'Notified'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SKIPPED', 'Skipped')], default='WAITING', max_length=16)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_approvals_acted', to=settings.AUTH_USER_MODEL)),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='finance.invoicepaymentapproval')),
                ('required_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_approval_steps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['step_order'],
                'unique_together': {('approval', 'step_order')},
            },
        ),
        migrations.AddIndex(
            model_name='invoicepaymentapproval',
            index=models.Index(fields=['restaurant', 'status', 'started_at'], name='finance_inv_restaur_45cacf_idx'),
        ),
    ]
