# Generated by Django 4.2.13 on 2026-07-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_payguard_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='proof_of_payment',
            field=models.FileField(blank=True, help_text='Receipt / transfer confirmation attached after payment.', null=True, upload_to='invoices/proof/'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='returned_reason',
            field=models.TextField(blank=True, default='', help_text='Why the invoice was returned for correction.'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('PENDING_APPROVAL', 'Pending approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned'), ('OPEN', 'Open'), ('PAYMENT_IN_PROGRESS', 'Payment in progress'), ('PAID', 'Paid'), ('PAYMENT_FAILED', 'Payment failed'), ('VOIDED', 'Voided')], default='OPEN', max_length=24),
        ),
    ]
