# Generated by Django 4.2.13 on 2026-07-30 06:19

import core.storage_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_invoice_lifecycle_proof_of_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='attachment',
            field=models.FileField(blank=True, help_text='Original invoice scan (image or PDF) from WhatsApp / upload.', null=True, upload_to=core.storage_paths.invoice_upload_path),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='photo',
            field=models.ImageField(blank=True, help_text='Snapshot of the printed/PDF invoice.', null=True, upload_to=core.storage_paths.invoice_photo_upload_path),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='proof_of_payment',
            field=models.FileField(blank=True, help_text='Receipt / transfer confirmation attached after payment.', null=True, upload_to=core.storage_paths.payment_proof_upload_path),
        ),
    ]
