# Generated by Django 5.2.16 on 2026-08-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_invoice_audit_event'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='invoiceauditevent',
            new_name='finance_inv_invoice_8f5392_idx',
            old_name='finance_inv_invoice_6a1b0d_idx',
        ),
        migrations.RenameIndex(
            model_name='invoiceauditevent',
            new_name='finance_inv_restaur_c8e834_idx',
            old_name='finance_inv_restaur_8c4f2a_idx',
        ),
        migrations.AlterField(
            model_name='invoiceauditevent',
            name='event_type',
            field=models.CharField(choices=[('CREATED', 'Created'), ('OCR_COMPLETED', 'OCR completed'), ('DATA_EDITED', 'Data edited'), ('VALIDATED', 'Validated'), ('APPROVAL_REQUESTED', 'Approval requested'), ('APPROVAL_NOTIFIED', 'Approver notified'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('INFO_REQUESTED', 'More information requested'), ('RETURNED', 'Returned for correction'), ('PAYMENT_RECORDED', 'Payment recorded'), ('PROOF_UPLOADED', 'Proof uploaded'), ('ASSIGNED', 'Assigned'), ('VOIDED', 'Voided'), ('PO_MATCHED', 'PO matched'), ('NOTIFICATION_SENT', 'Notification sent'), ('MIYA_ACTION', 'Miya action'), ('WHATSAPP_ACTION', 'WhatsApp action'), ('COMMENT', 'Comment')], db_index=True, max_length=32),
        ),
    ]
