# Generated by Django 5.1.4 on 2025-10-30 15:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClockEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('in', 'Clock In'), ('out', 'Clock Out'), ('break_start', 'Break Start'), ('break_end', 'Break End')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(upload_to='clock_photos/')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clock_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
