# Generated by Django 5.1.4 on 2025-11-11 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clockevent',
            name='location_encrypted',
            field=models.TextField(db_column='location_encrypted', default=''),
        ),
    ]
