# Generated by Django 5.1.4 on 2025-11-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0002_clockevent_location_encrypted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockevent',
            name='location_encrypted',
            field=models.TextField(db_column='location_encrypted'),
        ),
    ]
