# Generated by Django 4.2.13 on 2026-02-26 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_morocco_features'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduling', '0014_morocco_features'),
        ('timeclock', '0003_add_clock_event_performed_by_override_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opening_float', models.DecimalField(decimal_places=2, default=0, help_text='Cash in drawer at shift start (MAD)', max_digits=10)),
                ('expected_cash', models.DecimalField(blank=True, decimal_places=2, help_text='POS-reported cash sales for the shift', max_digits=10, null=True)),
                ('counted_cash', models.DecimalField(blank=True, decimal_places=2, help_text='Staff-reported cash in drawer at shift end', max_digits=10, null=True)),
                ('variance', models.DecimalField(blank=True, decimal_places=2, help_text='counted - (opening_float + expected_cash)', max_digits=10, null=True)),
                ('variance_reason', models.TextField(blank=True, help_text='Staff explanation for variance')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cash_counts/')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('COUNTED', 'Counted'), ('VERIFIED', 'Verified by Manager'), ('FLAGGED', 'Flagged — Variance')], default='OPEN', max_length=20)),
                ('manager_notes', models.TextField(blank=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('counted_at', models.DateTimeField(blank=True, null=True)),
                ('session_date', models.DateField(help_text='Date of the cash session')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_sessions', to='accounts.restaurant')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_sessions', to='scheduling.assignedshift')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_sessions', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_cash_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cash_sessions',
                'ordering': ['-session_date', '-opened_at'],
                'indexes': [models.Index(fields=['restaurant', 'session_date'], name='cash_sessio_restaur_cbe2cd_idx'), models.Index(fields=['staff', 'session_date'], name='cash_sessio_staff_i_1b151b_idx')],
            },
        ),
    ]
