# Generated by Django 4.2.10 on 2026-04-18 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0005_clockevent_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='clockevent',
            name='location_mismatch',
            field=models.BooleanField(default=False),
        ),
    ]
