# Generated by Django 5.1.4 on 2025-11-05 16:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_type', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Shift', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('break_duration', models.IntegerField(default=30, help_text='Break duration in minutes')),
                ('position_requirements', models.JSONField(blank=True, help_text='Required skills/certifications for this position', null=True)),
                ('tasks', models.JSONField(default=list)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_pattern', models.CharField(blank=True, max_length=50, null=True)),
                ('recurrence_end_date', models.DateField(blank=True, null=True)),
                ('color', models.CharField(default='#3498db', max_length=20)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('safety_briefing_required', models.BooleanField(default=False)),
                ('safety_briefing_completed', models.BooleanField(default=False)),
                ('safety_briefing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('ppe_requirements', models.JSONField(blank=True, help_text='Required PPE for this shift', null=True)),
                ('safety_compliance_status', models.CharField(choices=[('COMPLIANT', 'Compliant'), ('NON_COMPLIANT', 'Non-Compliant'), ('NEEDS_REVIEW', 'Needs Review'), ('NOT_APPLICABLE', 'Not Applicable')], default='NOT_APPLICABLE', max_length=20)),
                ('safety_compliance_notes', models.TextField(blank=True)),
                ('is_open_for_bidding', models.BooleanField(default=False)),
                ('bidding_deadline', models.DateTimeField(blank=True, null=True)),
                ('preferred_staff', models.JSONField(blank=True, help_text='List of staff IDs who have bid for this shift', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('backup_data', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_schedules', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='accounts.restaurant')),
                ('safety_briefing_completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_briefings', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('previous_data', models.JSONField()),
                ('new_data', models.JSONField()),
                ('change_type', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted')], max_length=20)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='staff.schedule')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_notifications', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='staff.schedule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('availability_type', models.CharField(choices=[('REGULAR', 'Regular Availability'), ('TIME_OFF', 'Time Off Request'), ('PREFERRED', 'Preferred Shift'), ('UNAVAILABLE', 'Unavailable'), ('EMERGENCY', 'Emergency Unavailability')], default='REGULAR', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied'), ('CANCELLED', 'Cancelled')], default='APPROVED', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('day_of_week', models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='For recurring availability patterns', null=True)),
                ('specific_date', models.DateField(blank=True, help_text='For specific date requests', null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('start_datetime', models.DateTimeField(blank=True, help_text='For specific datetime requests', null=True)),
                ('end_datetime', models.DateTimeField(blank=True, help_text='For specific datetime requests', null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('preferred_hours_per_week', models.IntegerField(blank=True, help_text='Preferred weekly hours', null=True)),
                ('max_consecutive_days', models.IntegerField(blank=True, help_text='Maximum consecutive working days', null=True)),
                ('min_hours_between_shifts', models.IntegerField(default=8, help_text='Minimum hours between shifts')),
                ('reason', models.TextField(blank=True, help_text='Reason for time-off or availability change', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or special requirements', null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True, null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_pattern', models.CharField(blank=True, choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Bi-weekly'), ('MONTHLY', 'Monthly')], max_length=20, null=True)),
                ('recurrence_end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_availability_requests', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['day_of_week', 'specific_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='staff_profiles/')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('hire_date', models.DateField(default=django.utils.timezone.now)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('certifications', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['staff', 'start_time'], name='staff_sched_staff_i_ed28f9_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['restaurant', 'start_time'], name='staff_sched_restaur_b0ad7b_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['status'], name='staff_sched_status_cf8ce8_idx'),
        ),
        migrations.AddIndex(
            model_name='staffavailability',
            index=models.Index(fields=['staff', 'availability_type'], name='staff_staff_staff_i_38bc8e_idx'),
        ),
        migrations.AddIndex(
            model_name='staffavailability',
            index=models.Index(fields=['staff', 'status'], name='staff_staff_staff_i_33c6bc_idx'),
        ),
        migrations.AddIndex(
            model_name='staffavailability',
            index=models.Index(fields=['specific_date'], name='staff_staff_specifi_df0e30_idx'),
        ),
        migrations.AddIndex(
            model_name='staffavailability',
            index=models.Index(fields=['day_of_week'], name='staff_staff_day_of__8ecd56_idx'),
        ),
    ]
