# Generated by Django 4.2.13 on 2025-11-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetyconcernreport',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='safety_concerns/'),
        ),
    ]
