# Generated by Django 5.2.7 on 2025-10-19 20:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customuser_role_alter_staffinvitation_role'),
        ('staff', '0002_category_order_product_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=10, unique=True)),
                ('capacity', models.IntegerField(default=2)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('NEEDS_CLEANING', 'Needs Cleaning'), ('OUT_OF_SERVICE', 'Out of Service')], default='AVAILABLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table', to='staff.order')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='accounts.restaurant')),
            ],
            options={
                'db_table': 'tables',
                'ordering': ['number'],
            },
        ),
    ]
