# Generated by Django 5.0 on 2025-10-27 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_remove_schedule_tasks_stafftask_schedule_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='tasks',
        ),
        migrations.DeleteModel(
            name='StaffTask',
        ),
        migrations.AddField(
            model_name='schedule',
            name='tasks',
            field=models.JSONField(default=list),
        ),
    ]
