# Generated by Django 5.2.7 on 2025-10-31 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_performancemetric_schedulechange_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffavailability',
            options={'ordering': ['day_of_week', 'specific_date', 'start_time']},
        ),
        migrations.AlterUniqueTogether(
            name='staffavailability',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='staffavailability',
            name='approval_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffavailability',
            name='availability_type',
            field=models.CharField(choices=[('REGULAR', 'Regular Availability'), ('TIME_OFF', 'Time Off Request'), ('PREFERRED', 'Preferred Shift'), ('UNAVAILABLE', 'Unavailable'), ('EMERGENCY', 'Emergency Unavailability')], default='REGULAR', max_length=20),
        ),
        migrations.AddField(
            model_name='staffavailability',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='staffavailability',
            name='end_datetime',
            field=models.DateTimeField(blank=True, help_text='For specific datetime requests', null=True),
        ),
        migrations.AddField(
            model_name='staffavailability',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffavailability',
            name='max_consecutive_days',
            field=models.IntegerField(blank=True, help_text='Maximum consecutive working days', null=True),
        ),
        migrations.AddField(
            model_name='staffavailability',
            name='min_hours_between_shifts',
            field=models.IntegerField(default=8, help_text='Minimum hours between shifts'),
        ),
        migrations.AddField(
            model_name='staffavailability',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes or special requirements', null=True),
        ),
        migrations.AddField(
            model_name='staffavailability',
            name='preferred_hours_per_week',
            field=models.IntegerField(blank=True, help_text='Preferred weekly hours', null=True),
        ),
        migrations.AddField(
            model_name='staffavailability',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10),
        ),
        migrations.AddField(
            model_name='staffavailability',
            name='reason',
            field=models.TextField(blank=True, help_text='Reason for time-off or availability change', null=True),
        ),
        migrations.AddField(
            model_name='staffavailability',
            name='recurrence_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffavailability',
            name='recurrence_pattern',
            field=models.CharField(blank=True, choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Bi-weekly'), ('MONTHLY', 'Monthly')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='staffavailability',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='staffavailability',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffavailability',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_availability_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffavailability',
            name='specific_date',
            field=models.DateField(blank=True, help_text='For specific date requests', null=True),
        ),
        migrations.AddField(
            model_name='staffavailability',
            name='start_datetime',
            field=models.DateTimeField(blank=True, help_text='For specific datetime requests', null=True),
        ),
        migrations.AddField(
            model_name='staffavailability',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied'), ('CANCELLED', 'Cancelled')], default='APPROVED', max_length=20),
        ),
        migrations.AddField(
            model_name='staffavailability',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='staffavailability',
            name='day_of_week',
            field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='For recurring availability patterns', null=True),
        ),
        migrations.AlterField(
            model_name='staffavailability',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffavailability',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='staffavailability',
            index=models.Index(fields=['staff', 'availability_type'], name='staff_staff_staff_i_38bc8e_idx'),
        ),
        migrations.AddIndex(
            model_name='staffavailability',
            index=models.Index(fields=['staff', 'status'], name='staff_staff_staff_i_33c6bc_idx'),
        ),
        migrations.AddIndex(
            model_name='staffavailability',
            index=models.Index(fields=['specific_date'], name='staff_staff_specifi_df0e30_idx'),
        ),
        migrations.AddIndex(
            model_name='staffavailability',
            index=models.Index(fields=['day_of_week'], name='staff_staff_day_of__8ecd56_idx'),
        ),
    ]
