# Generated by Django 4.2.10 on 2026-01-15 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_staffprofile_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduletask',
            name='checklist_progress',
            field=models.JSONField(blank=True, default=dict, help_text='Track completion of checklist items'),
        ),
    ]
