# Generated by Django 5.1.4 on 2026-01-16 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_scheduletask_checklist_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduletask',
            name='checklist_progress',
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='promotion_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='salary_type',
            field=models.CharField(choices=[('HOURLY', 'Hourly'), ('MONTHLY', 'Monthly')], default='HOURLY', max_length=10),
        ),
        migrations.DeleteModel(
            name='StaffDocument',
        ),
    ]
