# Generated by GPT-5.2 on 2026-01-27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_remove_assignedshift_assigned_sh_staff_i_dec37e_idx_and_more'),
        ('staff', '0006_staffdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetyconcernreport',
            name='incident_type',
            field=models.CharField(blank=True, default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='safetyconcernreport',
            name='occurred_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='safetyconcernreport',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_concerns', to='scheduling.assignedshift'),
        ),
        migrations.AddField(
            model_name='safetyconcernreport',
            name='audio_evidence',
            field=models.JSONField(blank=True, default=list),
        ),
    ]

