# Generated by GPT-5.2 on 2026-01-28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_restaurant_pos_location_id_restaurant_pos_oauth_data_and_more'),
        ('staff', '0007_safetyconcern_agent_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('staff_name', models.CharField(blank=True, default='', max_length=255)),
                ('staff_phone', models.CharField(blank=True, default='', max_length=32)),
                ('category', models.CharField(choices=[('DOCUMENT', 'Document'), ('HR', 'HR'), ('SCHEDULING', 'Scheduling'), ('PAYROLL', 'Payroll'), ('OPERATIONS', 'Operations'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ESCALATED', 'Escalated'), ('CLOSED', 'Closed')], default='PENDING', max_length=20)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('source', models.CharField(blank=True, default='whatsapp', help_text='Origin channel: whatsapp/lua/web', max_length=30)),
                ('external_id', models.CharField(blank=True, default='', help_text='External inquiry/ticket id if applicable', max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_requests', to='accounts.restaurant')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_staff_requests', to='accounts.customuser')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_requests', to='accounts.customuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffRequestComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(default='comment', help_text='comment|status_change|system', max_length=20)),
                ('body', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_request_comments', to='accounts.customuser')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='staff.staffrequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='staffrequest',
            index=models.Index(fields=['restaurant', 'status'], name='staff_staffr_restaur_5cf08b_idx'),
        ),
        migrations.AddIndex(
            model_name='staffrequest',
            index=models.Index(fields=['restaurant', 'created_at'], name='staff_staffr_restaur_6f5a19_idx'),
        ),
        migrations.AddIndex(
            model_name='staffrequest',
            index=models.Index(fields=['staff_phone'], name='staff_staffr_staff_p_e6a2b3_idx'),
        ),
        migrations.AddIndex(
            model_name='staffrequestcomment',
            index=models.Index(fields=['request', 'created_at'], name='staff_staffr_reques_4a4bb5_idx'),
        ),
    ]

