# Generated by Django 4.2.13 on 2026-01-29 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0008_staff_requests_inbox'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='staffrequest',
            new_name='staff_staff_restaur_711676_idx',
            old_name='staff_staffr_restaur_5cf08b_idx',
        ),
        migrations.RenameIndex(
            model_name='staffrequest',
            new_name='staff_staff_restaur_f682b0_idx',
            old_name='staff_staffr_restaur_6f5a19_idx',
        ),
        migrations.RenameIndex(
            model_name='staffrequest',
            new_name='staff_staff_staff_p_77eb65_idx',
            old_name='staff_staffr_staff_p_e6a2b3_idx',
        ),
        migrations.RenameIndex(
            model_name='staffrequestcomment',
            new_name='staff_staff_request_11ffc8_idx',
            old_name='staff_staffr_reques_4a4bb5_idx',
        ),
        migrations.AlterField(
            model_name='staffavailability',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_availability', to=settings.AUTH_USER_MODEL),
        ),
    ]
