# Generated by Django 5.1.4 on 2026-04-22 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_auditlog_memory_fields'),
        ('staff', '0011_safetyconcern_simplify_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='staffrequest',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_staff_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffrequest',
            name='transcription',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='staffrequest',
            name='transcription_language',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='staffrequest',
            name='voice_audio_url',
            field=models.URLField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='staffrequest',
            name='category',
            field=models.CharField(choices=[('DOCUMENT', 'Document'), ('HR', 'HR'), ('SCHEDULING', 'Scheduling'), ('PAYROLL', 'Payroll'), ('OPERATIONS', 'Operations'), ('MAINTENANCE', 'Maintenance'), ('RESERVATIONS', 'Reservations'), ('INVENTORY', 'Inventory'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='staffrequest',
            name='source',
            field=models.CharField(blank=True, default='whatsapp', help_text='Origin channel: whatsapp/lua/web/app', max_length=30),
        ),
        migrations.AddIndex(
            model_name='staffrequest',
            index=models.Index(fields=['assignee', 'status'], name='staffreq_assignee_status_idx'),
        ),
        migrations.AddIndex(
            model_name='staffrequest',
            index=models.Index(fields=['restaurant', 'category', 'status'], name='staffreq_rest_cat_stat_idx'),
        ),
    ]
