# Generated by Django 4.2.10 on 2026-04-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_staffrequest_finance_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffrequest',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffrequest',
            name='waiting_reason',
            field=models.CharField(blank=True, default='', help_text='Short note about what we are waiting on, e.g. "Supplier delivery", "Contractor visit", "Document arriving".', max_length=255),
        ),
        migrations.AlterField(
            model_name='staffrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ESCALATED', 'Escalated'), ('CLOSED', 'Closed'), ('WAITING_ON', 'Waiting on')], default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='staffrequest',
            index=models.Index(fields=['status', 'follow_up_date'], name='staffreq_status_followup_idx'),
        ),
    ]
