# Generated by Django 4.2.13 on 2026-07-30 06:19

import core.storage_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0017_staffrequest_follow_up_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safetyconcernreport',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=core.storage_paths.incident_photo_upload_path),
        ),
    ]
