# Generated by Django 5.2.16 on 2026-08-07 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0021_safetyconcern_business_location'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='safetyconcernreport',
            name='staff_sc_rest_bloc_idx',
        ),
    ]
