agent:
  agentId: baseAgent_agent_1762796132079_ob3ln5fkl
  orgId: c1234bab-fcdf-4a0f-966e-d09d1971e04f
  persona: |-
    You are Miya, the AI operations partner for Mizan. You manage luxury restaurants.

    AUTONOMOUS EXECUTION - NEVER ASK CLARIFYING QUESTIONS:
    1. Restaurant context is ALWAYS in your [SYSTEM: PERSISTENT CONTEXT] block. Use it directly.
    2. Today's date and current time are ALWAYS in your context. Use them directly.
    3. When scheduling staff:
       - ALWAYS use 'staff_lookup' FIRST to get the staff member's ID, role, and skills
       - ALWAYS use 'get_business_context' to resolve "lunch", "dinner", "morning" to specific times:
         * "lunch" = 12:00 to 15:00
         * "dinner" = 19:00 to 23:00
         * "morning" = 07:00 to 12:00
         * "afternoon" = 12:00 to 18:00
         * "evening" = 18:00 to 23:00
       - Use the staff member's EXISTING role from the database
       - Calculate "tomorrow" as today's date + 1 day
    4. If staff_lookup returns multiple matches, pick the most likely one or briefly ask which one.
    5. EXECUTE the action immediately. Do NOT ask for confirmation unless there's a genuine conflict.
    6. For identity questions, read the "User:" line in your context directly.

    WRONG: "What time does lunch start?" or "What is Fatima's role?"
    RIGHT: Use get_business_context and staff_lookup tools, then execute.
  welcomeMessage: ''
skills:
  - name: staff-orchestrator
    version: 1.0.36
    skillId: f8f28466-4864-4f0c-be40-9fd977c487e7
  - name: predictive-analyst
    version: 1.0.39
    skillId: 80c230d3-38e7-4020-9e74-2df61f48c520
  - name: restaurant-operations
    version: 1.0.28
    skillId: cb0eb026-6d53-4534-b763-9d3fed61006d
webhooks:
  - name: forecasting-events
    version: 1.0.0
    webhookId: 0e55fe4a-39d7-783i-e85a-eife2cb1a8f8
  - name: staff-management-events
    version: 2.0.0
    webhookId: 9d44ed39-28c6-672h-d749-dhed1ba098e7
  - name: user-authenticated
    version: 1.0.29
    webhookId: df2d840c-b80e-4e6b-98d8-af4e95c0d96a
  - name: user-events
    version: 1.0.5
    webhookId: 77f06520-d115-41b1-865e-afe7814ce82d
jobs:
  - jobId: 100b555b-4d19-4130-a879-92b5fbb594d3
    name: restaurant-health-check
    schedule:
      seconds: 300
      type: interval
    version: 3.0.0
  - jobId: 200c666c-5e20-5241-b980-a3c6gcc705e4
    name: menu-update-sync
    schedule:
      seconds: 3600
      type: interval
    version: 2.0.0
  - jobId: 300d777d-6f31-6352-ca91-b4d7hdd816f5
    name: guest-preference-analysis
    schedule:
      seconds: 86400
      type: interval
    version: 2.0.0
  - jobId: 400e888e-7f42-7463-dba2-c5e8iee927g6
    name: auto-staff-scheduler
    schedule:
      seconds: 604800
    version: 1.0.0
  - jobId: 500f999f-8g53-8574-ecb3-d6f9jff038h7
    name: performance-analytics
    schedule:
      seconds: 7200
      type: interval
    version: 2.0.0
  - jobId: 600g000g-9h64-9685-fdc4-e7g0kgg149i8
    name: sales-forecast-generator
    schedule:
      seconds: 43200
      type: interval
    version: 1.0.0
  - jobId: 700h111h-0i75-0796-ged5-f8h1lhh25aj9
    name: inventory-procurement-optimizer
    schedule:
      seconds: 21600
      type: interval
    version: 1.0.0
  - jobId: bc2d3a91-401d-453c-8c3f-ba02ab331d7c
    name: health-check-dev
    schedule:
      seconds: 300
      type: interval
    version: 1.0.0
  - jobId: 91d01b00-162d-4e56-94b9-3bcde2e13e3c
    name: agent-verification-dev
    schedule:
      seconds: 900
      type: interval
    version: 1.0.0
preprocessors:
  - capabilities:
      - menu-item-recognition
      - dietary-restriction-detection
      - occasion-understanding
      - preference-inference
      - allergy-flagging
    description: Understands dining-related intents, dietary needs, and culinary preferences
    name: dining-intent-recognition
    preprocessorId: preprocessor_239a74d6-2582-4146-9d5e-5d3ac6d9d317
    version: 3.0.0
  - capabilities:
      - guest-history-retrieval
      - preference-application
      - context-aware-processing
    description: Enhances requests with guest history, preferences, and current context
    name: guest-context-enrichment
    preprocessorId: preprocessor_34ab85e7-3693-5257-ae6f-6e4bd7a0e428
    version: 2.0.0
  - capabilities:
      - workload-assessment
      - skill-gap-analysis
      - urgency-calculation
      - resource-allocation
    description: Analyzes current staff workload and optimizes task distribution
    name: staff-workload-analyzer
    preprocessorId: preprocessor_45bc96f8-47a4-6368-bf7g-7f5cc8b1f539
    version: 2.0.0
  - capabilities:
      - historical-data-aggregation
      - external-factor-integration
      - confidence-level-calculation
      - scenario-modeling
    description: Processes forecasting requests and gathers relevant data sources
    name: forecasting-request-processor
    preprocessorId: preprocessor_56cd07g9-58b5-7479-cg8h-8g6dd2c26a4h
    version: 1.0.0
  - name: tenant-context-validation
    version: 2.2.17
    preprocessorId: preprocessor_730e748f-9bde-49b5-8bb2-69bc9f84eca2
postprocessors:
  - capabilities:
      - personalized-recommendations
      - anticipatory-suggestions
      - tone-matching
      - cultural-appropriateness
    description: Tailors responses with personal touches, recommendations, and anticipatory service
    name: personalized-response-crafting
    postprocessorId: postprocessor_5bb893a9-d2ee-4514-aefc-0eb080957fcf
    version: 3.0.0
  - capabilities:
      - surprise-and-delight
      - complementary-offers
      - memorable-touches
    description: Adds delightful touches and surprise elements to enhance dining experience
    name: experience-enhancement
    postprocessorId: postprocessor_6cc9a4ba-3eff-6625-bfgd-1fc191a068eg
    version: 2.0.0
  - capabilities:
      - task-prioritization
      - skill-based-assignment
      - efficiency-optimization
      - load-balancing
    description: Optimizes and assigns staff tasks based on real-time restaurant conditions
    name: staff-task-optimizer
    postprocessorId: postprocessor_7dda5bcb-4fgg-7736-cgh1-2gd2a2b179fh
    version: 2.0.0
  - capabilities:
      - data-visualization
      - actionable-insights
      - risk-assessment
      - recommendation-prioritization
    description: Formats and presents forecasts and inventory recommendations in actionable formats
    name: forecast-presentation
    postprocessorId: postprocessor_8eeb6cdc-5ghh-8847-dhi2-3he3b3c28agi
    version: 1.0.0
