# Generated by Django 4.2.13 on 2026-03-24 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_staffcapturedorder_fulfillment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='staffcapturedorder',
            new_name='dashboard_s_restaur_3df112_idx',
            old_name='dashboard_s_restaur_idx',
        ),
    ]
