# Generated by Django 4.2.13 on 2026-04-09 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_dashboard_custom_widget'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dashboardcustomwidget',
            new_name='dashboard_c_user_id_ab3ae4_idx',
            old_name='dashboard_c_user_id_2b8f91_idx',
        ),
        migrations.RenameIndex(
            model_name='dashboardcustomwidget',
            new_name='dashboard_c_restaur_816525_idx',
            old_name='dashboard_c_restaur_6c1a02_idx',
        ),
    ]
