# Generated by Django 4.2.13 on 2026-06-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='follow_up_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='follow_up_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='task',
            name='follow_up_max',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='task',
            name='last_follow_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='whatsapp_notified_at',
            field=models.DateTimeField(blank=True, help_text='When the initial WhatsApp notification was sent to the assignee.', null=True),
        ),
    ]
