# Generated by Django 4.2.13 on 2026-06-18 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_task_custom_widget'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='task',
            name='dashboard_t_rest_cu_status_idx',
        ),
    ]
