# Generated by Django 4.2.13 on 2026-06-18 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_dashboardcustomwidget_routing_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardcustomwidget',
            name='routing_keywords',
            field=models.JSONField(blank=True, default=list, help_text="Keywords that route Miya-created tasks into this tile (e.g. ['kasbah'] for 'Event Kasbah Dif')."),
        ),
    ]
