# Generated by Django 4.2.13 on 2026-07-10 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0016_alter_dashboardcustomwidget_routing_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffcapturedorder',
            name='detected_station',
            field=models.CharField(blank=True, default='', help_text='Auto-detected: Floor / Bar / Kitchen / Other from sender role', max_length=20),
        ),
        migrations.AddField(
            model_name='staffcapturedorder',
            name='manager_validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffcapturedorder',
            name='requires_manager_validation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='manager_validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='manager_validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_tasks_validated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='proof_media_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='task',
            name='proof_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='require_photo_proof',
            field=models.BooleanField(default=False, help_text='Assignee should send a photo via WhatsApp before completion.'),
        ),
        migrations.AddField(
            model_name='task',
            name='requires_manager_validation',
            field=models.BooleanField(default=False, help_text="When true, task shows 'not validated by manager' until validated. Non-blocking."),
        ),
    ]
