# Generated by Django 4.2.13 on 2026-07-30 06:19

import core.storage_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_task_proof_caption_submitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=core.storage_paths.task_attachment_upload_path),
        ),
    ]
