# Generated by Django 4.2.13 on 2026-07-31 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0037_fix_morocco_country_code'),
        ('dashboard', '0021_s3_org_scoped_upload_paths'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffDailyProgressReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_date', models.DateField(db_index=True)),
                ('staff_name', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, default='', max_length=40)),
                ('is_absent', models.BooleanField(default=False)),
                ('total', models.PositiveSmallIntegerField(default=0)),
                ('done', models.PositiveSmallIntegerField(default=0)),
                ('open', models.PositiveSmallIntegerField(default=0)),
                ('pct', models.PositiveSmallIntegerField(default=0)),
                ('captured_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_daily_progress_reports', to='accounts.restaurant')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_progress_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dashboard_staff_daily_progress_reports',
                'ordering': ['-report_date', 'staff_name'],
                'indexes': [models.Index(fields=['restaurant', '-report_date'], name='dashboard_s_restaur_340969_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='staffdailyprogressreport',
            constraint=models.UniqueConstraint(fields=('restaurant', 'report_date', 'staff'), name='uniq_staff_daily_progress_report'),
        ),
    ]
