# Generated by Django 5.2.16 on 2026-08-07 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_task_location'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='task',
            name='dash_task_rest_loc_idx',
        ),
    ]
