# Generated by Django 5.1.4 on 2025-11-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='general_settings',
            field=models.JSONField(default=dict),
        ),
    ]
