# Generated by Django 5.0 on 2025-10-24 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffAvailability',
        ),
    ]
