# Generated by Django 5.1.4 on 2025-11-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_restaurant_general_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='settings_schema_version',
            field=models.IntegerField(default=1),
        ),
    ]
