# Generated by Django 4.2.13 on 2025-12-03 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userinvitation_email_invitationdeliverylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvitation',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
