# Generated by Django 5.1.4 on 2025-10-26 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_pin_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pin_code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
