# Generated by Django 4.2.25 on 2025-10-18 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_restaurant_latitude_restaurant_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='accounts.restaurant'),
        ),
    ]
