# Generated by Django 5.2.7 on 2025-10-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_geo_fence_radius_restaurant_radius_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='timezone',
            field=models.CharField(default='America/New_York', max_length=50),
        ),
    ]
