# Generated by Django 4.2.13 on 2025-12-03 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userinvitation_extra_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffinvitation',
            old_name='token',
            new_name='invitation_token',
        ),
        migrations.RenameField(
            model_name='staffinvitation',
            old_name='created_at',
            new_name='sent_at',
        ),
        migrations.AlterField(
            model_name='staffinvitation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
