# Generated by Django 4.2.25 on 2025-10-18 11:44

from django.db import migrations, models
import django.db.models.deletion


def set_default_restaurant_for_customuser(apps, schema_editor):
    CustomUser = apps.get_model('accounts', 'CustomUser')
    Restaurant = apps.get_model('accounts', 'Restaurant')

    # Get or create a default restaurant
    default_restaurant = Restaurant.objects.first()
    if not default_restaurant:
        default_restaurant = Restaurant.objects.create(
            name="Default Restaurant",
            address="123 Main St",
            phone="555-1234",
            email="default@example.com",
            latitude=0.0,
            longitude=0.0,
            geo_fence_radius=0.0
        )

    # Set default restaurant for users with null restaurant
    CustomUser.objects.filter(restaurant__isnull=True).update(restaurant=default_restaurant)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_options_remove_customuser_pin_code_and_more'),
    ]

    operations = [
        migrations.RunPython(set_default_restaurant_for_customuser, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='customuser',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='accounts.restaurant'),
        ),
    ]
