# Generated by Django 5.2.7 on 2025-10-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_restaurant_currency_restaurant_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='operating_hours',
            field=models.JSONField(default=dict),
        ),
    ]
