# Generated by Django 4.2.13 on 2025-12-16 00:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_whatsapp_invitations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffinvitation',
            name='invitation_token',
        ),
        migrations.RemoveField(
            model_name='staffinvitation',
            name='sent_at',
        ),
        migrations.AddField(
            model_name='staffinvitation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffinvitation',
            name='token',
            field=models.CharField(default='default_token', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staffinvitation',
            name='email',
            field=models.EmailField(default='example@email.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinvitation',
            name='email',
            field=models.EmailField(default='example@email.com', max_length=254),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='InvitationDeliveryLog',
        ),
    ]
