# Generated by Django 5.2.7 on 2025-10-27 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rbac_models'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='role',
            name='unique_role_per_restaurant',
        ),
        migrations.RemoveConstraint(
            model_name='rolepermission',
            name='unique_role_permission',
        ),
        migrations.RemoveConstraint(
            model_name='userrole',
            name='unique_user_role_restaurant',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_rest_ts_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_user_ts_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_action_idx',
        ),
        migrations.RemoveIndex(
            model_name='userinvitation',
            name='rbac_user_i_rest_st_idx',
        ),
        migrations.RemoveIndex(
            model_name='userinvitation',
            name='rbac_user_i_token_idx',
        ),
        migrations.RemoveIndex(
            model_name='userinvitation',
            name='rbac_user_i_email_idx',
        ),
        migrations.AlterUniqueTogether(
            name='staffinvitation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('restaurant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'permission')},
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'restaurant', 'role')},
        ),
    ]
