# Generated by Django 5.2.7 on 2025-10-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_restaurant_operating_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='automatic_clock_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='break_duration',
            field=models.IntegerField(default=30),
        ),
    ]
