# Generated by Django 5.2.7 on 2025-10-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_restaurant_automatic_clock_out_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='email_notifications',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='push_notifications',
            field=models.JSONField(default=dict),
        ),
    ]
