# Generated by Django 5.1.4 on 2026-01-16 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_invitationdeliverylog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffinvitation',
            old_name='token',
            new_name='invitation_token',
        ),
        migrations.RenameField(
            model_name='staffinvitation',
            old_name='created_at',
            new_name='sent_at',
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='join_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='promotion_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='salary_type',
            field=models.CharField(choices=[('HOURLY', 'Hourly'), ('MONTHLY', 'Monthly')], default='HOURLY', max_length=20),
        ),
        migrations.AlterField(
            model_name='staffinvitation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='userinvitation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
