# Generated by Django 5.2.7 on 2025-10-28 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_pin_code'),
        ('accounts', '0006_remove_role_unique_role_per_restaurant_and_more'),
    ]

    operations = [
    ]
