# Generated by Django 4.2.25 on 2025-10-19 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pin_code',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
    ]
