# Generated by Django 5.2.7 on 2025-10-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_pin_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pin_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
