# Generated by Django 5.2.7 on 2025-10-31 12:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_merge_20251028_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='radius',
            field=models.DecimalField(blank=True, decimal_places=2, default=100, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
