# Generated by Django 5.2.7 on 2025-11-01 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_restaurant_radius'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffinvitation',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
