# Generated by Django 5.1.4 on 2026-01-16 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_staffdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('CHEF', 'Chef'), ('WAITER', 'Waiter'), ('KITCHEN_HELP', 'Kitchen Help'), ('BARTENDER', 'Bartender'), ('RECEPTIONIST', 'Receptionist'), ('CLEANER', 'Cleaner'), ('SECURITY', 'Security'), ('CASHIER', 'Cashier')], max_length=20),
        ),
        migrations.AlterField(
            model_name='staffinvitation',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('CHEF', 'Chef'), ('WAITER', 'Waiter'), ('KITCHEN_HELP', 'Kitchen Help'), ('BARTENDER', 'Bartender'), ('RECEPTIONIST', 'Receptionist'), ('CLEANER', 'Cleaner'), ('SECURITY', 'Security'), ('CASHIER', 'Cashier')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userinvitation',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('CHEF', 'Chef'), ('WAITER', 'Waiter'), ('KITCHEN_HELP', 'Kitchen Help'), ('BARTENDER', 'Bartender'), ('RECEPTIONIST', 'Receptionist'), ('CLEANER', 'Cleaner'), ('SECURITY', 'Security'), ('CASHIER', 'Cashier')], max_length=20),
        ),
    ]
