# Generated by Django 5.1.4 on 2026-01-16 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customuser_role_alter_staffinvitation_role_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffDocument',
        ),
    ]
