# Generated by Django 5.2.7 on 2025-10-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_staffprofile_emergency_contact_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('CHEF', 'Chef'), ('WAITER', 'Waiter'), ('CLEANER', 'Cleaner'), ('CASHIER', 'Cashier')], max_length=20),
        ),
        migrations.AlterField(
            model_name='staffinvitation',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('CHEF', 'Chef'), ('WAITER', 'Waiter'), ('CLEANER', 'Cleaner'), ('CASHIER', 'Cashier')], max_length=20),
        ),
    ]
