# Generated by Django 5.2.7 on 2025-11-02 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_restaurant_address'),
        ('accounts', '0009_staffinvitation_extra_data_staffprofile_department'),
    ]

    operations = [
    ]
