# Generated by Django 5.2.7 on 2025-11-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_merge_20251102_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_failed_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_successful_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('LOGIN', 'Login'), ('LOGIN_FAILED', 'Login Failed'), ('LOGIN_PIN', 'PIN Login'), ('LOGIN_PIN_FAILED', 'PIN Login Failed'), ('LOGOUT', 'Logout'), ('ACCOUNT_LOCKED', 'Account Locked'), ('ACCOUNT_UNLOCKED', 'Account Unlocked'), ('PASSWORD_CHANGED', 'Password Changed'), ('PIN_CHANGED', 'PIN Changed'), ('PERMISSION_CHANGE', 'Permission Changed'), ('ORDER_ACTION', 'Order Action'), ('INVENTORY_ACTION', 'Inventory Action'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
