# Generated by Django 4.2.11 on 2025-11-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_add_restaurant_general_settings_schema_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffinvitation',
            name='invitation_pin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
