# Generated by Django 4.2.13 on 2026-01-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_customuser_preferred_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='pos_location_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='pos_oauth_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='pos_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
