# Generated by Django 4.2.13 on 2026-01-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_restaurant_pos_location_id_restaurant_pos_oauth_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='max_weekly_hours',
            field=models.DecimalField(decimal_places=2, default=40.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='min_rest_hours',
            field=models.DecimalField(decimal_places=2, default=11.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_type',
            field=models.CharField(choices=[('FINE_DINING', 'Fine Dining'), ('CASUAL_DINING', 'Casual Dining'), ('FAST_FOOD', 'Fast Food'), ('CAFE', 'Cafe/Bakery'), ('BAR', 'Bar/Lounge'), ('OTHER', 'Other')], default='CASUAL_DINING', max_length=50),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='pos_provider',
            field=models.CharField(choices=[('STRIPE', 'Stripe'), ('SQUARE', 'Square'), ('TOAST', 'Toast'), ('LIGHTSPEED', 'Lightspeed'), ('CLOVER', 'Clover'), ('CUSTOM', 'Custom API'), ('NONE', 'Not Configured')], default='NONE', max_length=50),
        ),
    ]
