# Generated by Django 4.2.10 on 2026-02-06 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_restaurant_labor_target_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffActivationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(db_index=True, help_text='Normalized digits; phone is the only identity', max_length=20)),
                ('first_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('CHEF', 'Chef'), ('WAITER', 'Waiter'), ('KITCHEN_HELP', 'Kitchen Help'), ('BARTENDER', 'Bartender'), ('RECEPTIONIST', 'Receptionist'), ('CLEANER', 'Cleaner'), ('SECURITY', 'Security'), ('CASHIER', 'Cashier')], default='WAITER', max_length=20)),
                ('status', models.CharField(choices=[('NOT_ACTIVATED', 'Not Activated'), ('ACTIVATED', 'Activated')], db_index=True, default='NOT_ACTIVATED', max_length=20)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_activation_records', to='accounts.restaurant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_activation_record', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'staff_activation_records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone', 'status'], name='staff_activ_phone_3c2ab9_idx'), models.Index(fields=['restaurant', 'status'], name='staff_activ_restaur_8717a7_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='staffactivationrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'NOT_ACTIVATED')), fields=('restaurant', 'phone'), name='unique_not_activated_per_restaurant_phone'),
        ),
    ]
