# Generated by Django 4.2.10 on 2026-02-06 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_staff_activation_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffactivationrecord',
            name='batch_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='CSV batch identifier for this upload', max_length=64),
        ),
        migrations.AddField(
            model_name='staffactivationrecord',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_activation_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staffactivationrecord',
            name='status',
            field=models.CharField(choices=[('NOT_ACTIVATED', 'Pending Activation'), ('ACTIVATED', 'Activated')], db_index=True, default='NOT_ACTIVATED', max_length=20),
        ),
    ]
