# Generated by Django 4.2.13 on 2026-02-08 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_staffrestaurantlink'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='staffrestaurantlink',
            new_name='staff_resta_restaur_657633_idx',
            old_name='staff_resta_restaur_idx',
        ),
        migrations.RenameIndex(
            model_name='staffrestaurantlink',
            new_name='staff_resta_user_id_d35b6f_idx',
            old_name='staff_resta_user_id_idx',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='timezone',
            field=models.CharField(default='Africa/Casablanca', max_length=50),
        ),
        migrations.AlterField(
            model_name='staffrestaurantlink',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('CHEF', 'Chef'), ('WAITER', 'Waiter'), ('KITCHEN_HELP', 'Kitchen Help'), ('BARTENDER', 'Bartender'), ('RECEPTIONIST', 'Receptionist'), ('CLEANER', 'Cleaner'), ('SECURITY', 'Security'), ('CASHIER', 'Cashier')], default='WAITER', max_length=20),
        ),
    ]
