# Generated by Django 4.2.13 on 2026-02-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_rename_staff_resta_restaur_idx_staff_resta_restaur_657633_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='country_code',
            field=models.CharField(default='MA', help_text='ISO country code for labor law & compliance', max_length=5),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='iftar_time',
            field=models.TimeField(blank=True, help_text='Daily Iftar time (auto-adjusts prep schedules)', null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='prayer_break_minutes',
            field=models.IntegerField(default=15, help_text='Minutes allocated for prayer breaks'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='ramadan_mode',
            field=models.BooleanField(default=False, help_text='Enable Ramadan-specific scheduling and workflows'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='suhoor_time',
            field=models.TimeField(blank=True, help_text='Daily Suhoor time', null=True),
        ),
    ]
