# Generated by Django 4.2.13 on 2026-03-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_restaurant_reservation_oauth_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='reservation_oauth_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
