# Generated by Django 4.2.13 on 2026-03-25 10:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_restaurant_reservation_oauth_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='EatNowWebhookDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delivery_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('event_type', models.CharField(blank=True, default='', max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eatnow_webhook_deliveries', to='accounts.restaurant')),
            ],
            options={
                'db_table': 'eatnow_webhook_deliveries',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['restaurant', '-received_at'], name='eatnow_webh_restaur_344b44_idx')],
            },
        ),
    ]
