# Generated by Django 4.2.13 on 2026-03-25 10:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_eatnow_webhook_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='EatNowReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(db_index=True, max_length=128)),
                ('status', models.CharField(blank=True, default='', max_length=128)),
                ('group_size', models.IntegerField(blank=True, null=True)),
                ('reservation_date', models.DateField(blank=True, db_index=True, null=True)),
                ('reservation_time', models.CharField(blank=True, default='', max_length=32)),
                ('guest_name', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=64)),
                ('email', models.CharField(blank=True, default='', max_length=254)),
                ('notes', models.TextField(blank=True, default='')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(blank=True, default='', max_length=64)),
                ('raw_reservation', models.JSONField(blank=True, default=dict)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eatnow_reservations', to='accounts.restaurant')),
            ],
            options={
                'db_table': 'eatnow_reservations',
                'ordering': ['reservation_date', 'reservation_time', 'guest_name'],
                'indexes': [models.Index(fields=['restaurant', 'is_deleted', 'reservation_date'], name='eatnow_rese_restaur_da4092_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='eatnowreservation',
            constraint=models.UniqueConstraint(fields=('restaurant', 'external_id'), name='uniq_eatnow_res_restaurant_external'),
        ),
    ]
