# Generated by Django 4.2.13 on 2026-04-09 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_custom_role_label_and_custom_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('CHEF', 'Chef'), ('WAITER', 'Waiter'), ('KITCHEN_HELP', 'Kitchen Help'), ('BARTENDER', 'Bartender'), ('RECEPTIONIST', 'Receptionist'), ('CLEANER', 'Cleaner'), ('SECURITY', 'Security'), ('CASHIER', 'Cashier'), ('CUSTOM', 'Custom')], max_length=20),
        ),
        migrations.AlterField(
            model_name='staffactivationrecord',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('CHEF', 'Chef'), ('WAITER', 'Waiter'), ('KITCHEN_HELP', 'Kitchen Help'), ('BARTENDER', 'Bartender'), ('RECEPTIONIST', 'Receptionist'), ('CLEANER', 'Cleaner'), ('SECURITY', 'Security'), ('CASHIER', 'Cashier'), ('CUSTOM', 'Custom')], default='WAITER', max_length=20),
        ),
        migrations.AlterField(
            model_name='staffinvitation',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('CHEF', 'Chef'), ('WAITER', 'Waiter'), ('KITCHEN_HELP', 'Kitchen Help'), ('BARTENDER', 'Bartender'), ('RECEPTIONIST', 'Receptionist'), ('CLEANER', 'Cleaner'), ('SECURITY', 'Security'), ('CASHIER', 'Cashier'), ('CUSTOM', 'Custom')], max_length=20),
        ),
        migrations.AlterField(
            model_name='staffrestaurantlink',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('CHEF', 'Chef'), ('WAITER', 'Waiter'), ('KITCHEN_HELP', 'Kitchen Help'), ('BARTENDER', 'Bartender'), ('RECEPTIONIST', 'Receptionist'), ('CLEANER', 'Cleaner'), ('SECURITY', 'Security'), ('CASHIER', 'Cashier'), ('CUSTOM', 'Custom')], default='WAITER', max_length=20),
        ),
        migrations.AlterField(
            model_name='userinvitation',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('CHEF', 'Chef'), ('WAITER', 'Waiter'), ('KITCHEN_HELP', 'Kitchen Help'), ('BARTENDER', 'Bartender'), ('RECEPTIONIST', 'Receptionist'), ('CLEANER', 'Cleaner'), ('SECURITY', 'Security'), ('CASHIER', 'Cashier'), ('CUSTOM', 'Custom')], max_length=20),
        ),
    ]
