# Generated by Django 4.2.13 on 2026-04-16 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermissionSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=32)),
                ('permissions', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permission_sets', to='accounts.restaurant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_permission_edits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rbac_role_permission_sets',
                'indexes': [models.Index(fields=['restaurant', 'role'], name='rbac_role_p_restaur_4104b9_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='rolepermissionset',
            constraint=models.UniqueConstraint(fields=('restaurant', 'role'), name='uniq_role_permission_set_per_restaurant'),
        ),
    ]
