# Generated by Django 4.2.10 on 2026-04-18 00:39

from django.db import migrations, models
import django.db.models.deletion


def backfill_primary_location(apps, schema_editor):
    """For every existing staff user, set ``primary_location`` to their
    restaurant's primary BusinessLocation (created in 0029). Users without a
    restaurant or whose restaurant has no primary location are left as-is —
    the field is nullable and legacy code paths still work.
    """
    CustomUser = apps.get_model('accounts', 'CustomUser')
    BusinessLocation = apps.get_model('accounts', 'BusinessLocation')

    # Build restaurant_id -> primary location id map once to avoid N+1.
    primary_by_restaurant = {
        row['restaurant_id']: row['id']
        for row in BusinessLocation.objects.filter(
            is_primary=True, is_active=True
        ).values('id', 'restaurant_id')
    }

    users_to_update = []
    for user in CustomUser.objects.filter(
        restaurant__isnull=False, primary_location__isnull=True
    ).only('id', 'restaurant_id'):
        loc_id = primary_by_restaurant.get(user.restaurant_id)
        if loc_id:
            user.primary_location_id = loc_id
            users_to_update.append(user)

    if users_to_update:
        CustomUser.objects.bulk_update(users_to_update, ['primary_location'], batch_size=500)


def noop_reverse(apps, schema_editor):
    """Reverse is a no-op; clearing FKs would lose information and the field
    is simply removed by the reverse schema operation."""
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_business_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='allowed_locations',
            field=models.ManyToManyField(blank=True, related_name='allowed_staff', to='accounts.businesslocation'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='managed_locations',
            field=models.ManyToManyField(blank=True, related_name='managers', to='accounts.businesslocation'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='primary_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_staff', to='accounts.businesslocation'),
        ),
        migrations.RunPython(backfill_primary_location, noop_reverse),
    ]
