# Generated by Django 4.2.10 on 2026-04-18 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_customuser_allowed_locations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='onboarding_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='onboarding_state',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
