# Generated by Django 4.2.13 on 2026-04-22 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_restaurant_onboarding_completed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermissionSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permissions', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permission_sets', to='accounts.restaurant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_permission_edits', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_override', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rbac_user_permission_sets',
                'indexes': [models.Index(fields=['restaurant', 'user'], name='rbac_user_p_restaur_7a4dde_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='userpermissionset',
            constraint=models.UniqueConstraint(fields=('restaurant', 'user'), name='uniq_user_permission_set_per_restaurant'),
        ),
    ]
