# Generated by Django 4.2.10 on 2026-04-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_auditlog_memory_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
