# Generated by Django 5.1.4 on 2025-10-26 01:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('total_staff_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('staff_on_shift', models.IntegerField(default=0)),
                ('late_arrivals', models.IntegerField(default=0)),
                ('absences', models.IntegerField(default=0)),
                ('attendance_details', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_reports', to='accounts.restaurant')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('restaurant', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DailySalesReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_orders', models.IntegerField(default=0)),
                ('avg_order_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('top_selling_items', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_sales_reports', to='accounts.restaurant')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('restaurant', 'date')},
            },
        ),
        migrations.CreateModel(
            name='InventoryReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('total_inventory_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('low_stock_items', models.JSONField(default=list)),
                ('waste_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('stock_adjustment_summary', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_reports', to='accounts.restaurant')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('restaurant', 'date')},
            },
        ),
    ]
