# Generated by Django 5.2.7 on 2025-10-22 15:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('SALES_SUMMARY', 'Sales Summary'), ('ATTENDANCE_OVERVIEW', 'Attendance Overview'), ('INVENTORY_STATUS', 'Inventory Status'), ('SHIFT_PERFORMANCE', 'Shift Performance'), ('OTHER', 'Other')], max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField()),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='accounts.restaurant')),
            ],
            options={
                'db_table': 'reports',
                'ordering': ('-generated_at',),
            },
        ),
    ]
