# Generated by Django 4.2.13 on 2026-02-04 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_add_labor_budget_and_policy'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='laborbudget',
            new_name='labor_budge_restaur_4e1878_idx',
            old_name='labor_budge_restaur_idx',
        ),
    ]
