# Generated by Django 4.2.13 on 2026-02-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0004_rename_labor_budge_restaur_idx_labor_budge_restaur_4e1878_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborpolicy',
            name='mandatory_rest_day_per_week',
            field=models.BooleanField(default=True, help_text='Morocco requires 1 rest day per 7-day period'),
        ),
        migrations.AddField(
            model_name='laborpolicy',
            name='overtime_rate_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.25, help_text='e.g. 1.25 = 125% pay for overtime', max_digits=4),
        ),
        migrations.AlterField(
            model_name='laborpolicy',
            name='late_threshold_minutes',
            field=models.IntegerField(default=5, help_text='Minutes after shift start to count as late'),
        ),
        migrations.AlterField(
            model_name='laborpolicy',
            name='max_hours_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, default=10, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='laborpolicy',
            name='max_hours_per_week',
            field=models.DecimalField(blank=True, decimal_places=2, default=44, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='laborpolicy',
            name='min_rest_hours_between_shifts',
            field=models.DecimalField(blank=True, decimal_places=2, default=12, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='laborpolicy',
            name='overtime_after_hours_per_week',
            field=models.DecimalField(blank=True, decimal_places=2, default=44, max_digits=5, null=True),
        ),
    ]
