# Generated by Django 4.2.13 on 2026-07-31 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0037_fix_morocco_country_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantAutomation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=False)),
                ('trigger_type', models.CharField(max_length=64)),
                ('trigger_config', models.JSONField(blank=True, default=dict)),
                ('steps', models.JSONField(blank=True, default=list)),
                ('template_id', models.CharField(blank=True, default='', max_length=64)),
                ('run_count', models.PositiveIntegerField(default=0)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('stop_miya_on_match', models.BooleanField(default=False, help_text='When True, skip Miya for this message after automation runs.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_automations', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automations', to='accounts.restaurant')),
            ],
            options={
                'db_table': 'tenant_automations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationRunLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('trigger_event', models.CharField(blank=True, default='', max_length=64)),
                ('success', models.BooleanField(default=True)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='automations.tenantautomation')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.restaurant')),
            ],
            options={
                'db_table': 'automation_run_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tenantautomation',
            index=models.Index(fields=['restaurant', 'is_active'], name='tenant_auto_restaur_0ac418_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantautomation',
            index=models.Index(fields=['restaurant', 'trigger_type'], name='tenant_auto_restaur_1aae73_idx'),
        ),
    ]
