# Generated by Django 4.2.13 on 2026-02-26 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_morocco_features'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCountSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='IN_PROGRESS', max_length=20)),
                ('items_total', models.IntegerField(default=0)),
                ('items_counted', models.IntegerField(default=0)),
                ('current_item_index', models.IntegerField(default=0, help_text='Index into the ordered item list')),
                ('count_data', models.JSONField(default=dict, help_text='Map of item_id -> {counted: Decimal, expected: Decimal, variance: Decimal}')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('count_date', models.DateField()),
                ('counted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_count_sessions', to='accounts.restaurant')),
            ],
            options={
                'db_table': 'inventory_count_sessions',
                'ordering': ['-count_date'],
            },
        ),
        migrations.CreateModel(
            name='WasteEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(help_text='Free-text name (used when item not in inventory system)', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, help_text='Auto-calculated from inventory cost_per_unit or manual', max_digits=10)),
                ('reason', models.CharField(choices=[('EXPIRED', 'Expired'), ('SPOILED', 'Spoiled'), ('OVERPRODUCTION', 'Overproduction'), ('DROPPED', 'Dropped / Damaged'), ('RETURNED', 'Customer Return'), ('QUALITY', 'Quality Issue'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='waste_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('waste_date', models.DateField(help_text='Date the waste occurred')),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_entries', to='inventory.inventoryitem')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_reports', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_entries', to='accounts.restaurant')),
            ],
            options={
                'db_table': 'waste_entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['restaurant', 'waste_date'], name='waste_entri_restaur_b5e026_idx')],
            },
        ),
    ]
