# Generated by Django 5.2.7 on 2025-10-27 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_phase4_enhancements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryaudit',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='inventoryaudit',
            name='started_by',
        ),
        migrations.RemoveField(
            model_name='inventoryaudititem',
            name='audit',
        ),
        migrations.RemoveField(
            model_name='inventoryaudititem',
            name='inventory_item',
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='inventory_item',
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='menu_item',
        ),
        migrations.RemoveField(
            model_name='stockalert',
            name='acknowledged_by',
        ),
        migrations.RemoveField(
            model_name='stockalert',
            name='inventory_item',
        ),
        migrations.RemoveField(
            model_name='stocklevel',
            name='inventory_item',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='inventory_item',
        ),
        migrations.RemoveField(
            model_name='suppliercontact',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='supplierprice',
            name='inventory_item',
        ),
        migrations.RemoveField(
            model_name='supplierprice',
            name='supplier',
        ),
        migrations.DeleteModel(
            name='Forecast',
        ),
        migrations.DeleteModel(
            name='InventoryAudit',
        ),
        migrations.DeleteModel(
            name='InventoryAuditItem',
        ),
        migrations.DeleteModel(
            name='RecipeIngredient',
        ),
        migrations.DeleteModel(
            name='StockAlert',
        ),
        migrations.DeleteModel(
            name='StockLevel',
        ),
        migrations.DeleteModel(
            name='StockMovement',
        ),
        migrations.DeleteModel(
            name='SupplierContact',
        ),
        migrations.DeleteModel(
            name='SupplierPrice',
        ),
    ]
