# Generated by Django 4.2.13 on 2026-01-28 10:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_restaurant_pos_location_id_restaurant_pos_oauth_data_and_more'),
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSExternalEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('SQUARE', 'Square'), ('TOAST', 'Toast'), ('CLOVER', 'Clover'), ('CUSTOM', 'Custom')], max_length=20)),
                ('external_event_id', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=255)),
                ('payload', models.JSONField(default=dict)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_external_events', to='accounts.restaurant')),
            ],
            options={
                'db_table': 'pos_external_events',
            },
        ),
        migrations.CreateModel(
            name='POSExternalObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('SQUARE', 'Square'), ('TOAST', 'Toast'), ('CLOVER', 'Clover'), ('CUSTOM', 'Custom')], max_length=20)),
                ('object_type', models.CharField(max_length=100)),
                ('object_id', models.CharField(max_length=255)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_external_objects', to='accounts.restaurant')),
            ],
            options={
                'db_table': 'pos_external_objects',
                'indexes': [models.Index(fields=['restaurant', 'provider', 'object_type'], name='pos_externa_restaur_a6f0b7_idx'), models.Index(fields=['provider', 'object_type', 'object_id'], name='pos_externa_provide_0eaba9_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='posexternalobject',
            constraint=models.UniqueConstraint(fields=('restaurant', 'provider', 'object_type', 'object_id'), name='uniq_pos_external_object'),
        ),
        migrations.AddIndex(
            model_name='posexternalevent',
            index=models.Index(fields=['restaurant', 'provider', 'received_at'], name='pos_externa_restaur_c384f3_idx'),
        ),
        migrations.AddIndex(
            model_name='posexternalevent',
            index=models.Index(fields=['provider', 'external_event_id'], name='pos_externa_provide_0ee414_idx'),
        ),
        migrations.AddConstraint(
            model_name='posexternalevent',
            constraint=models.UniqueConstraint(fields=('restaurant', 'provider', 'external_event_id'), name='uniq_pos_external_event'),
        ),
    ]
