# Generated by Django 4.2.10 on 2026-04-18 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_posexternalevent_posexternalobject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('RESERVED', 'Reserved'), ('NEEDS_CLEANING', 'Needs Cleaning'), ('MAINTENANCE', 'Maintenance')], default='AVAILABLE', max_length=20),
        ),
    ]
