# Generated by Django 4.2.13 on 2026-06-18 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='compliancereminder',
            new_name='payroll_com_restaur_7f062b_idx',
            old_name='payroll_com_rest_due_idx',
        ),
        migrations.RenameIndex(
            model_name='payslip',
            new_name='payroll_pay_restaur_52fbca_idx',
            old_name='payroll_pay_rest_per_idx',
        ),
        migrations.RenameIndex(
            model_name='payslip',
            new_name='payroll_pay_restaur_d1f063_idx',
            old_name='payroll_pay_staff_idx',
        ),
        migrations.RenameIndex(
            model_name='temperaturereading',
            new_name='payroll_tem_restaur_ac436b_idx',
            old_name='payroll_temp_rest_dt_idx',
        ),
        migrations.AddIndex(
            model_name='temperaturereading',
            index=models.Index(fields=['restaurant', 'equipment', 'recorded_at'], name='payroll_tem_restaur_5bb38c_idx'),
        ),
    ]
