# Generated by Django 4.2.10 on 2026-07-15 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0035_staffprofile_monthly_salary'),
        ('payroll', '0002_rename_payroll_com_rest_due_idx_payroll_com_restaur_7f062b_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('BUSINESS_REGISTRATION', 'Business registration'), ('INSURANCE', 'Insurance'), ('FIRE_EXTINGUISHER', 'Fire extinguisher inspection'), ('HYGIENE', 'Hygiene / food safety certificate'), ('HEALTH_PERMIT', 'Health permit'), ('LIQUOR_LICENSE', 'Liquor license'), ('EQUIPMENT_INSPECTION', 'Equipment inspection'), ('OTHER', 'Other')], default='OTHER', max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('reference_number', models.CharField(blank=True, default='', max_length=128)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('remind_days_before', models.PositiveSmallIntegerField(default=30, help_text='Start reminding this many days before expiry')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=16)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_documents_created', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_documents', to='accounts.restaurant')),
            ],
            options={
                'ordering': ['expires_at', 'title'],
                'indexes': [models.Index(fields=['restaurant', 'status', 'expires_at'], name='payroll_com_restaur_c93247_idx'), models.Index(fields=['restaurant', 'document_type'], name='payroll_com_restaur_c8f64b_idx')],
            },
        ),
    ]
