# Generated by Django 4.2.13 on 2026-01-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='external_provider',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='external_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='external_provider',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='menucategory',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False), ('external_provider__isnull', False)), fields=('restaurant', 'external_provider', 'external_id'), name='uniq_menucategory_external'),
        ),
        migrations.AddConstraint(
            model_name='menuitem',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False), ('external_provider__isnull', False)), fields=('restaurant', 'external_provider', 'external_id'), name='uniq_menuitem_external'),
        ),
    ]
