# Generated by Django 5.1.4 on 2025-11-29 02:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('scheduling', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('step_type', models.CharField(choices=[('CHECK', 'Simple Check'), ('MEASUREMENT', 'Measurement Input'), ('PHOTO', 'Photo Evidence'), ('SIGNATURE', 'Digital Signature'), ('NOTE', 'Text Note'), ('CONDITIONAL', 'Conditional Logic')], max_length=20)),
                ('order', models.PositiveIntegerField()),
                ('is_required', models.BooleanField(default=True)),
                ('requires_photo', models.BooleanField(default=False)),
                ('requires_note', models.BooleanField(default=False)),
                ('requires_signature', models.BooleanField(default=False)),
                ('measurement_type', models.CharField(blank=True, choices=[('TEMPERATURE', 'Temperature'), ('COUNT', 'Count/Quantity'), ('TIME', 'Time Duration'), ('WEIGHT', 'Weight'), ('VOLUME', 'Volume'), ('PERCENTAGE', 'Percentage'), ('CUSTOM', 'Custom Unit')], max_length=20, null=True)),
                ('measurement_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('conditional_logic', models.JSONField(blank=True, default=dict, help_text='JSON defining conditional step logic')),
                ('validation_rules', models.JSONField(blank=True, default=dict, help_text='JSON defining validation rules')),
                ('depends_on_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependent_steps', to='checklists.checkliststep')),
            ],
            options={
                'db_table': 'checklist_steps',
                'ordering': ['template', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], default='NOT_STARTED', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('completion_notes', models.TextField(blank=True, null=True)),
                ('supervisor_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_version', models.IntegerField(default=1)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_checklists', to=settings.AUTH_USER_MODEL)),
                ('assigned_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists', to='scheduling.assignedshift')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_checklists', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_executions', to='scheduling.shifttask')),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_executions', to='checklists.checkliststep')),
            ],
            options={
                'db_table': 'checklist_executions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistStepResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('text_response', models.TextField(blank=True, null=True)),
                ('measurement_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('boolean_response', models.BooleanField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('signature_data', models.TextField(blank=True, help_text='Base64 encoded signature image', null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_responses', to='checklists.checklistexecution')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='checklists.checkliststep')),
            ],
            options={
                'db_table': 'checklist_step_responses',
            },
        ),
        migrations.CreateModel(
            name='ChecklistEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_type', models.CharField(choices=[('PHOTO', 'Photo'), ('VIDEO', 'Video'), ('DOCUMENT', 'Document'), ('AUDIO', 'Audio Recording')], max_length=20)),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('file_path', models.CharField(help_text='Path to stored file', max_length=500)),
                ('thumbnail_path', models.CharField(blank=True, help_text='Path to thumbnail if applicable', max_length=500, null=True)),
                ('visibility', models.CharField(choices=[('PRIVATE', 'Private'), ('TEAM', 'Team'), ('ORGANIZATION', 'Organization')], default='TEAM', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata like GPS, timestamp, etc.')),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('step_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='checklists.checkliststepresponse')),
            ],
            options={
                'db_table': 'checklist_evidence',
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_checklist_actions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_checklist_actions', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_checklist_actions', to=settings.AUTH_USER_MODEL)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='checklists.checklistexecution')),
                ('step_response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='checklists.checkliststepresponse')),
            ],
            options={
                'db_table': 'checklist_actions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estimated_duration', models.DurationField(blank=True, null=True)),
                ('requires_supervisor_approval', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_checklist_templates', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_templates', to='accounts.restaurant')),
                ('task_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_templates', to='scheduling.tasktemplate')),
            ],
            options={
                'db_table': 'checklist_templates',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='checkliststep',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='checklists.checklisttemplate'),
        ),
        migrations.AddField(
            model_name='checklistexecution',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='checklists.checklisttemplate'),
        ),
        migrations.AddIndex(
            model_name='checkliststepresponse',
            index=models.Index(fields=['execution', 'step'], name='checklist_s_executi_797ed7_idx'),
        ),
        migrations.AddIndex(
            model_name='checkliststepresponse',
            index=models.Index(fields=['status'], name='checklist_s_status_652feb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='checkliststepresponse',
            unique_together={('execution', 'step')},
        ),
        migrations.AddIndex(
            model_name='checklistevidence',
            index=models.Index(fields=['step_response'], name='checklist_e_step_re_3692fb_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistevidence',
            index=models.Index(fields=['evidence_type'], name='checklist_e_evidenc_cdc449_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistaction',
            index=models.Index(fields=['execution'], name='checklist_a_executi_8b07a9_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistaction',
            index=models.Index(fields=['assigned_to', 'status'], name='checklist_a_assigne_738926_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistaction',
            index=models.Index(fields=['priority', 'status'], name='checklist_a_priorit_518be6_idx'),
        ),
        migrations.AddIndex(
            model_name='checklisttemplate',
            index=models.Index(fields=['restaurant', 'category'], name='checklist_t_restaur_668712_idx'),
        ),
        migrations.AddIndex(
            model_name='checklisttemplate',
            index=models.Index(fields=['is_active'], name='checklist_t_is_acti_33f037_idx'),
        ),
        migrations.AddIndex(
            model_name='checkliststep',
            index=models.Index(fields=['template', 'order'], name='checklist_s_templat_3aace3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='checkliststep',
            unique_together={('template', 'order')},
        ),
        migrations.AddIndex(
            model_name='checklistexecution',
            index=models.Index(fields=['assigned_to', 'status'], name='checklist_e_assigne_ea75de_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistexecution',
            index=models.Index(fields=['template', 'status'], name='checklist_e_templat_2bced6_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistexecution',
            index=models.Index(fields=['due_date'], name='checklist_e_due_dat_ecc39c_idx'),
        ),
    ]
