# Generated by Django 5.1.4 on 2025-11-26 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('checklists', '0001_initial'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistexecution',
            name='assigned_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists', to='scheduling.assignedshift'),
        ),
        migrations.AddField(
            model_name='checklistexecution',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_checklists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checklistexecution',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_executions', to='scheduling.shifttask'),
        ),
        migrations.AddField(
            model_name='checklistaction',
            name='execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='checklists.checklistexecution'),
        ),
        migrations.AddField(
            model_name='checkliststep',
            name='depends_on_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependent_steps', to='checklists.checkliststep'),
        ),
        migrations.AddField(
            model_name='checklistexecution',
            name='current_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_executions', to='checklists.checkliststep'),
        ),
        migrations.AddField(
            model_name='checkliststepresponse',
            name='execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_responses', to='checklists.checklistexecution'),
        ),
        migrations.AddField(
            model_name='checkliststepresponse',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='checklists.checkliststep'),
        ),
        migrations.AddField(
            model_name='checklistevidence',
            name='step_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='checklists.checkliststepresponse'),
        ),
        migrations.AddField(
            model_name='checklistaction',
            name='step_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='checklists.checkliststepresponse'),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_checklist_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_templates', to='accounts.restaurant'),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='task_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_templates', to='scheduling.tasktemplate'),
        ),
        migrations.AddField(
            model_name='checkliststep',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='checklists.checklisttemplate'),
        ),
        migrations.AddField(
            model_name='checklistexecution',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='checklists.checklisttemplate'),
        ),
        migrations.AddIndex(
            model_name='checkliststepresponse',
            index=models.Index(fields=['execution', 'step'], name='checklist_s_executi_797ed7_idx'),
        ),
        migrations.AddIndex(
            model_name='checkliststepresponse',
            index=models.Index(fields=['status'], name='checklist_s_status_652feb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='checkliststepresponse',
            unique_together={('execution', 'step')},
        ),
        migrations.AddIndex(
            model_name='checklistevidence',
            index=models.Index(fields=['step_response'], name='checklist_e_step_re_3692fb_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistevidence',
            index=models.Index(fields=['evidence_type'], name='checklist_e_evidenc_cdc449_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistaction',
            index=models.Index(fields=['execution'], name='checklist_a_executi_8b07a9_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistaction',
            index=models.Index(fields=['assigned_to', 'status'], name='checklist_a_assigne_738926_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistaction',
            index=models.Index(fields=['priority', 'status'], name='checklist_a_priorit_518be6_idx'),
        ),
        migrations.AddIndex(
            model_name='checklisttemplate',
            index=models.Index(fields=['restaurant', 'category'], name='checklist_t_restaur_668712_idx'),
        ),
        migrations.AddIndex(
            model_name='checklisttemplate',
            index=models.Index(fields=['is_active'], name='checklist_t_is_acti_33f037_idx'),
        ),
        migrations.AddIndex(
            model_name='checkliststep',
            index=models.Index(fields=['template', 'order'], name='checklist_s_templat_3aace3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='checkliststep',
            unique_together={('template', 'order')},
        ),
        migrations.AddIndex(
            model_name='checklistexecution',
            index=models.Index(fields=['assigned_to', 'status'], name='checklist_e_assigne_ea75de_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistexecution',
            index=models.Index(fields=['template', 'status'], name='checklist_e_templat_2bced6_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistexecution',
            index=models.Index(fields=['due_date'], name='checklist_e_due_dat_ecc39c_idx'),
        ),
    ]
