# Generated by Django 4.2.13 on 2026-07-31 19:48

import core.storage_paths
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0003_compliance_document'),
        ('accounts', '0037_fix_morocco_country_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploader_phone', models.CharField(blank=True, default='', max_length=32)),
                ('source', models.CharField(choices=[('WIDGET', 'Dashboard widget'), ('WHATSAPP', 'WhatsApp')], default='WIDGET', max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('mime_type', models.CharField(blank=True, default='', max_length=128)),
                ('file', models.FileField(blank=True, default='', upload_to=core.storage_paths.tenant_document_upload_path)),
                ('storage_path', models.CharField(blank=True, default='', max_length=512)),
                ('file_url', models.URLField(blank=True, default='', max_length=1000)),
                ('category', models.CharField(blank=True, default='other', max_length=64)),
                ('summary', models.TextField(blank=True, default='')),
                ('extracted_text', models.TextField(blank=True, default='')),
                ('parse_metadata', models.JSONField(blank=True, default=dict)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compliance_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_files', to='payroll.compliancedocument')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_documents', to='accounts.restaurant')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_documents_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['restaurant', '-created_at'], name='miya_tenant_restaur_48049a_idx'), models.Index(fields=['restaurant', 'category'], name='miya_tenant_restaur_5f367c_idx')],
            },
        ),
    ]
