# Generated by Django 5.2.16 on 2026-08-07 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miya', '0004_operational_memory'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tenantdocument',
            name='miya_tenant_vend_idx',
        ),
        migrations.RemoveIndex(
            model_name='tenantdocument',
            name='miya_tenant_exp_idx',
        ),
        migrations.RenameIndex(
            model_name='operationalevent',
            new_name='miya_operat_restaur_dd5582_idx',
            old_name='miya_operat_restaur_7a1b01_idx',
        ),
        migrations.RenameIndex(
            model_name='operationalevent',
            new_name='miya_operat_restaur_606e7d_idx',
            old_name='miya_operat_restaur_9c2d02_idx',
        ),
        migrations.RenameIndex(
            model_name='operationalevent',
            new_name='miya_operat_restaur_75b5fa_idx',
            old_name='miya_operat_restaur_3e4f03_idx',
        ),
        migrations.RenameIndex(
            model_name='workingmemorysnapshot',
            new_name='miya_workin_restaur_60c032_idx',
            old_name='miya_workin_restaur_5a6b04_idx',
        ),
    ]
