# Generated by Django 5.2.16 on 2026-08-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miya', '0006_tenantdocument_versioning'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tenantdocument',
            new_name='miya_tenant_restaur_07c255_idx',
            old_name='miya_tenant_rest_hash_idx',
        ),
        migrations.RenameIndex(
            model_name='tenantdocument',
            new_name='miya_tenant_restaur_1e8c65_idx',
            old_name='miya_tenant_fam_cur_idx',
        ),
        migrations.AlterField(
            model_name='tenantdocument',
            name='document_family_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Groups all versions of the same logical document.', null=True),
        ),
        migrations.AlterField(
            model_name='tenantdocument',
            name='is_current',
            field=models.BooleanField(db_index=True, default=True, help_text='True for the latest version within a document family.'),
        ),
    ]
