# Generated by Django 5.1.4 on 2025-11-17 09:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('SHIFT_ASSIGNED', 'Shift Assigned'), ('SHIFT_UPDATED', 'Shift Updated'), ('SHIFT_CANCELLED', 'Shift Cancelled'), ('SHIFT_REMINDER', 'Shift Reminder'), ('TASK_ASSIGNED', 'Task Assigned'), ('TASK_COMPLETED', 'Task Completed'), ('TASK_OVERDUE', 'Task Overdue'), ('AVAILABILITY_REQUEST', 'Availability Request'), ('AVAILABILITY_APPROVED', 'Availability Approved'), ('AVAILABILITY_DENIED', 'Availability Denied'), ('COMPLIANCE_ALERT', 'Compliance Alert'), ('SAFETY_BRIEFING', 'Safety Briefing'), ('ANNOUNCEMENT', 'Announcement'), ('BREAK_REQUEST', 'Break Request'), ('EMERGENCY', 'Emergency'), ('SYSTEM_ALERT', 'System Alert'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Additional structured data')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channels_sent', models.JSONField(default=list, help_text='Channels through which notification was sent')),
                ('delivery_status', models.JSONField(default=dict, help_text='Delivery status for each channel')),
                ('related_shift_id', models.UUIDField(blank=True, help_text='Related shift ID', null=True)),
                ('related_task_id', models.UUIDField(blank=True, help_text='Related task ID', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When notification expires', null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='notification_attachments/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='notifications.notification')),
            ],
            options={
                'db_table': 'notification_attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Investigating'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='notifications.notification')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_issues',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=20)),
                ('recipient_address', models.CharField(help_text='Email, phone number, or device token', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('BOUNCED', 'Bounced')], default='PENDING', max_length=20)),
                ('attempt_count', models.IntegerField(default=1)),
                ('external_id', models.CharField(blank=True, help_text='External service message ID', max_length=255, null=True)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='notifications.notification')),
            ],
            options={
                'db_table': 'notification_logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('whatsapp_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('shift_notifications', models.BooleanField(default=True)),
                ('task_notifications', models.BooleanField(default=True)),
                ('availability_notifications', models.BooleanField(default=True)),
                ('compliance_notifications', models.BooleanField(default=True)),
                ('emergency_notifications', models.BooleanField(default=True)),
                ('announcement_notifications', models.BooleanField(default=True)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='Start of quiet hours', null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='End of quiet hours', null=True)),
                ('digest_enabled', models.BooleanField(default=False, help_text='Receive daily digest instead of individual notifications')),
                ('digest_time', models.TimeField(blank=True, help_text='Time to send daily digest', null=True)),
                ('whatsapp_number', models.CharField(blank=True, help_text='WhatsApp number for notifications', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template_type', models.CharField(choices=[('SHIFT_ASSIGNED', 'Shift Assigned'), ('SHIFT_UPDATED', 'Shift Updated'), ('SHIFT_CANCELLED', 'Shift Cancelled'), ('SHIFT_REMINDER', 'Shift Reminder'), ('TASK_ASSIGNED', 'Task Assigned'), ('AVAILABILITY_REQUEST', 'Availability Request'), ('COMPLIANCE_ALERT', 'Compliance Alert'), ('EMERGENCY', 'Emergency')], max_length=30)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('PUSH', 'Push Notification'), ('SMS', 'SMS')], max_length=20)),
                ('subject_template', models.CharField(blank=True, help_text='Subject/title template', max_length=255, null=True)),
                ('body_template', models.TextField(help_text='Message body template with placeholders')),
                ('available_variables', models.JSONField(default=list, help_text='List of available template variables')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_templates',
            },
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('device_type', models.CharField(choices=[('ANDROID', 'Android'), ('IOS', 'iOS'), ('WEB', 'Web Browser')], default='WEB', max_length=10)),
                ('device_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device Token',
                'verbose_name_plural': 'Device Tokens',
                'db_table': 'device_tokens',
                'indexes': [models.Index(fields=['user', 'is_active'], name='device_toke_user_id_e99165_idx'), models.Index(fields=['token'], name='device_toke_token_e218ea_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_583549_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'notification_type'], name='notificatio_recipie_b1a229_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='notificatio_created_e4c995_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['priority'], name='notificatio_priorit_17ee5f_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationattachment',
            index=models.Index(fields=['notification'], name='notificatio_notific_bd1a5b_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationissue',
            index=models.Index(fields=['status'], name='notificatio_status_7dfc17_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationissue',
            index=models.Index(fields=['created_at'], name='notificatio_created_c57e6a_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['notification', 'channel'], name='notificatio_notific_6b2a25_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['status'], name='notificatio_status_95b675_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['sent_at'], name='notificatio_sent_at_85d1ed_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['template_type', 'channel'], name='notificatio_templat_bc4d66_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['is_active'], name='notificatio_is_acti_f33840_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationtemplate',
            unique_together={('template_type', 'channel', 'is_default')},
        ),
    ]
