# Generated by Django 4.2.13 on 2025-12-16 00:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('state', models.CharField(default='idle', max_length=50)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('last_interaction_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'whatsapp_sessions',
                'indexes': [models.Index(fields=['phone'], name='whatsapp_se_phone_d27709_idx'), models.Index(fields=['state'], name='whatsapp_se_state_a04fd6_idx')],
            },
        ),
    ]
