# Generated by Django 4.2.13 on 2026-01-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('SHIFT_ASSIGNED', 'Shift Assigned'), ('SHIFT_UPDATED', 'Shift Updated'), ('SHIFT_CANCELLED', 'Shift Cancelled'), ('SHIFT_REMINDER', 'Shift Reminder'), ('TASK_ASSIGNED', 'Task Assigned'), ('TASK_COMPLETED', 'Task Completed'), ('TASK_OVERDUE', 'Task Overdue'), ('AVAILABILITY_REQUEST', 'Availability Request'), ('AVAILABILITY_APPROVED', 'Availability Approved'), ('AVAILABILITY_DENIED', 'Availability Denied'), ('STAFF_REQUEST', 'Staff Request'), ('COMPLIANCE_ALERT', 'Compliance Alert'), ('SAFETY_BRIEFING', 'Safety Briefing'), ('ANNOUNCEMENT', 'Announcement'), ('BREAK_REQUEST', 'Break Request'), ('EMERGENCY', 'Emergency'), ('SYSTEM_ALERT', 'System Alert'), ('INVITATION', 'Staff Invitation'), ('OTHER', 'Other')], default='OTHER', max_length=30),
        ),
    ]
