# Generated by Django 4.2.13 on 2026-02-08 01:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_whatsappmessageprocessed_whatsappsession_phone_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappmessageprocessed',
            name='processed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='whatsappmessageprocessed',
            index=models.Index(fields=['wamid'], name='whatsapp_me_wamid_368939_idx'),
        ),
    ]
