# Generated by Django 5.1.4 on 2025-11-29 02:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.UUIDField()),
                ('rating', models.PositiveSmallIntegerField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('comments', models.TextField(blank=True, null=True)),
                ('completed_at', models.DateTimeField()),
                ('hours_decimal', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_reviews', to='accounts.restaurant')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attendance_shift_reviews',
            },
        ),
        migrations.CreateModel(
            name='ReviewLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_likes', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='attendance.shiftreview')),
            ],
            options={
                'db_table': 'attendance_review_likes',
            },
        ),
        migrations.AddIndex(
            model_name='shiftreview',
            index=models.Index(fields=['staff', 'completed_at'], name='attendance__staff_i_480488_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftreview',
            index=models.Index(fields=['restaurant', 'completed_at'], name='attendance__restaur_8b25fb_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftreview',
            index=models.Index(fields=['rating'], name='attendance__rating_0261e0_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewlike',
            index=models.Index(fields=['review'], name='attendance__review__df3a24_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewlike',
            index=models.Index(fields=['user'], name='attendance__user_id_417c3e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewlike',
            unique_together={('review', 'user')},
        ),
    ]
