# Generated by Django 5.1.4 on 2025-11-09 01:49

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # Depend on accounts initial migration to avoid missing node errors
        ('accounts', '0001_initial'),
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reviewlike',
            name='unique_review_user_like',
        ),
        migrations.AlterField(
            model_name='reviewlike',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shiftreview',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='reviewlike',
            unique_together={('review', 'user')},
        ),
        migrations.AddIndex(
            model_name='reviewlike',
            index=models.Index(fields=['review'], name='attendance__review__df3a24_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewlike',
            index=models.Index(fields=['user'], name='attendance__user_id_417c3e_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftreview',
            index=models.Index(fields=['staff', 'completed_at'], name='attendance__staff_i_480488_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftreview',
            index=models.Index(fields=['restaurant', 'completed_at'], name='attendance__restaur_8b25fb_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftreview',
            index=models.Index(fields=['rating'], name='attendance__rating_0261e0_idx'),
        ),
        migrations.AlterModelTable(
            name='reviewlike',
            table='attendance_review_likes',
        ),
        migrations.AlterModelTable(
            name='shiftreview',
            table='attendance_shift_reviews',
        ),
    ]
